In [1]:
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
from matplotlib import pyplot
from datetime import datetime
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [2]:
DataFrame = pd.read_csv('../Data.csv')

In [3]:
RB = DataFrame[DataFrame['Position'] == 'RB']

In [4]:
RB = RB.drop(columns = ['Week','Position','Game','Unnamed: 0'])

In [5]:
RB = RB.drop(columns = ['PassingYards','PassingTDs','Ints'])

In [6]:
RB = RB.groupby(['Name','Year']).sum()

In [7]:
RB

                     Fantasy Points  Rush Attempts  Rush Yards  Fumbles  \
Name           Year
AJ Dillon      2020            36.0             46         242        0
               2021           172.0            187         803        1
               2022           157.0            186         770        0
               2023           108.0            178         613        0
Aaron Jones    2019           304.0            236        1084        2
...                             ...            ...         ...      ...
Zack Moss      2023           159.0            183         794        0
Zamir White    2022             4.0             17          70        0
               2023            67.0            104         451        1
Zonovan Knight 2022            54.0             85         300        0
               2023             2.0              3          13        0

                     RushTDs  Receptions  Receiving Yards  Receiving TDs
Name           Year
AJ Dillon      2020        2         2.0             21.0            0.0
               2021        5        34.0            313.0            2.0
               2022        7        28.0            206.0            0.0
               2023        2        22.0            223.0            0.0
Aaron Jones    2019       16        49.0            474.0            3.0
...                      ...         ...              ...            ...
Zack Moss      2023        5        27.0            192.0            2.0
Zamir White    2022        0         0.0              0.0            0.0
               2023        1        15.0             98.0            0.0
Zonovan Knight 2022        1        13.0            100.0            0.0
               2023        0         1.0              8.0            0.0

[792 rows x 8 columns]

In [8]:
RB.reset_index(inplace=True)

In [9]:
RB.set_index('Year', inplace = True)

In [10]:
RB.index = pd.to_datetime(RB.index, format='%Y')

In [11]:
RB

,Name,Fantasy Points,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
Year,,,,,,,,,
2020-01-01,AJ Dillon,36.0,46,242,0,2,2.0,21.0,0.0
2021-01-01,AJ Dillon,172.0,187,803,1,5,34.0,313.0,2.0
2022-01-01,AJ Dillon,157.0,186,770,0,7,28.0,206.0,0.0
2023-01-01,AJ Dillon,108.0,178,613,0,2,22.0,223.0,0.0
2019-01-01,Aaron Jones,304.0,236,1084,2,16,49.0,474.0,3.0
...,...,...,...,...,...,...,...,...,...
2023-01-01,Zack Moss,159.0,183,794,0,5,27.0,192.0,2.0
2022-01-01,Zamir White,4.0,17,70,0,0,0.0,0.0,0.0
2023-01-01,Zamir White,67.0,104,451,1,1,15.0,98.0,0.0
2022-01-01,Zonovan Knight,54.0,85,300,0,1,13.0,100.0,0.0
2023-01-01,Zonovan Knight,2.0,3,13,0,0,1.0,8.0,0.0

In [12]:
RB['Style'] = ''
RB['RunningSkill'] = ''

In [13]:
RB.loc[(RB['Receptions'] >= 40), 'Style'] = 'ReceivngBack'
RB.loc[(RB['Receptions'] < 40) , 'Style'] = 'TraditionalRB'
RB.loc[(RB['Rush Yards'] > 400) & (RB['Rush Yards'] < 900), 'RunningSkill'] = 'RB2'
RB.loc[(RB['Rush Yards'] >= 900) , 'RunningSkill'] = 'RB1'
RB.loc[(RB['Rush Yards'] <= 400), 'RunningSkill'] = 'Backup'

In [14]:
X = RB.drop(['Fantasy Points'], axis=1)
y = RB['Fantasy Points']

categorical_features = ['Style', 'RunningSkill']
numeric_features = ['Rush Yards']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


X_train_subset = X_train[X_train.index.year < 2022]
y_train_subset = y_train[y_train.index.year < 2022]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2022]
y_test_subset = y_test[y_test.index.year == 2022]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 829.6706653989415
R-squared: 0.8989570503603337

In [15]:
X = RB.drop(['Fantasy Points'], axis=1)
y = RB['Fantasy Points']

numeric_features = ['Rush Yards']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
       
    ]
)


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


X_train_subset = X_train[X_train.index.year < 2022]
y_train_subset = y_train[y_train.index.year < 2022]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2022]
y_test_subset = y_test[y_test.index.year == 2022]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 1344.4400110610345
R-squared: 0.8362649301745869

In [16]:
X = RB.drop(['Fantasy Points'], axis=1)
y = RB['Fantasy Points']

numeric_features = ['RushTDs']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
       
    ]
)


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


X_train_subset = X_train[X_train.index.year < 2022]
y_train_subset = y_train[y_train.index.year < 2022]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2022]
y_test_subset = y_test[y_test.index.year == 2022]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 2057.364914808075
R-squared: 0.749440075264792

In [17]:
X = RB.drop(['Fantasy Points'], axis=1)
y = RB['Fantasy Points']

categorical_features = ['Style', 'RunningSkill']
numeric_features = ['RushTDs']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


X_train_subset = X_train[X_train.index.year < 2022]
y_train_subset = y_train[y_train.index.year < 2022]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2022]
y_test_subset = y_test[y_test.index.year == 2022]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 616.71875
R-squared: 0.9248917863473886

In [18]:
features = ['RushTDs', 'Rush Attempts']
target_variable = 'Rush Yards'

In [19]:
players = RB['Name'].unique()

# Create a dictionary to store predictions for each player
predictions_2024 = {}

for player in players:
    player_data = RB[RB['Name'] == player]
    time_series = player_data[features + [target_variable]]
    
    try:
        # Fit an ARIMA model
        model = ARIMA(time_series[target_variable], order=(1, 1, 1))  # Adjust the order as needed
        arima_result = model.fit()
        
        # Predict Fantasy Points for 2024
        start_date_2024 = datetime(2024, 1, 1)
        end_date_2024 = datetime(2024, 12, 31)
        y_pred_2024 = arima_result.predict(start=start_date_2024, end=end_date_2024, dynamic=False)
        
        # Store predictions in the dictionary
        predictions_2024[player] = y_pred_2024.values[-1]  # Only store the prediction for 2024
        
        
        
    except Exception as e:
        continue

In [20]:
predictions_2024

{'AJ Dillon': 555.4854276387794,
 'Aaron Jones': 736.1868469240364,
 'Adam Prentice': 16.77204159163947,
 'Adrian Peterson': -1102.7442018612073,
 'Alec Ingold': 2.8907645261622337,
 'Alexander Mattison': 628.1120761015268,
 'Alvin Kamara': 787.2110819513166,
 'Ameer Abdullah': 88.99538962018666,
 'Andy Janovich': 0.5416102839580668,
 'Anthony McFarland': 4.469231878265607,
 'Antonio Gibson': 293.0061624579571,
 'Austin Ekeler': 665.0889645249088,
 'Benjamin Snell': 122.93052335028489,
 'Boston Scott': 23.163895885515046,
 'C.J. Ham': 16.205641064158204,
 'Cam Akers': 167.00187184637025,
 'Carlos Hyde': 253.00262271709252,
 'Chase Edmonds': 289.3391834605108,
 'Chris Carson': -1174.9509655516117,
 'Chris Evans': 30.75570832548693,
 'Christian McCaffrey': 946.5041562642814,
 'Chuba Hubbard': 901.9401514079264,
 'Clyde Edwards-Helaire': 192.69232670295062,
 'Cordarrelle Patterson': -163.37478788165868,
 'Corey Clement': 57.793024227334556,
 'Craig Reynolds': 168.98712077692176,
 "D'Andre Swift": 1048.9660062271644,
 "D'Ernest Johnson": 170.2989493006136,
 "D'Onta Foreman": 418.21706622422045,
 'Dalvin Cook': 214.1469651959311,
 'Damien Harris': 22.711138787754983,
 'Dare Ogunbowale': 30.04354230358685,
 'Darrel Williams': 260.7530980042226,
 'Darrell Henderson': 147.22603491430758,
 'Darrynton Evans': 119.44894244269445,
 'David Johnson': 257.851201498117,
 'David Montgomery': 924.2020875839045,
 'DeeJay Dallas': 107.45068265237475,
 'Deon Jackson': 17.073505832258974,
 'Derrick Henry': 1400.8336837308732,
 'Devin Singletary': 897.9960437086565,
 'Devine Ozigbo': 4.2346375484165,
 'Devonta Freeman': 556.6112913592343,
 'Devontae Booker': 577.9785850994605,
 'Dontrell Hilliard': 144.89897968397898,
 'Duke Johnson': 181.63490152688212,
 'Dwayne Washington': 33.71911536408856,
 'Elijah Mitchell': 488.3781070847983,
 'Elijhaa Penny': 50.5715407308158,
 'Ezekiel Elliott': 399.13744337337766,
 'Gary Brightwell': 19.279429550845308,
 'Giovani Bernard': 159.91274078414975,
 'Greg Howell': 11.036528846744801,
 'Ito Smith': 96.3769169747745,
 'J.D. McKissic': 196.11852829099956,
 'J.J. Taylor': 13.574468276065504,
 'JaMycal Hasty': 95.83512385649392,
 'Jakob Johnson': 0.0,
 'Jalen Richard': -7.261412853751011,
 'Jamaal Williams': 580.1764435028982,
 'James Conner': 1244.7397708776355,
 'James Robinson': -906.7259436245749,
 'James White': -66.6418096112429,
 'Jason Cabinda': 7.0664653343436665,
 'Javonte Williams': 757.2097756020562,
 'Jaylen Samuels': 21.909884920476923,
 'Jeffery Wilson': 196.7696915798091,
 'Jerick McKinnon': 60.47511621210518,
 'Joe Mixon': 1003.1532629886233,
 'Jonathan Taylor': 1038.583084047203,
 'Jonathan Ward': 18.06631787385314,
 'Jonathan Williams': 43.67171716173954,
 'Jordan Howard': 403.8849707645185,
 'Josh Jacobs': 1010.4954961224619,
 'Joshua Kelley': 285.76891896656394,
 'Justin Jackson': 260.70833249157226,
 'Kalen Ballage': 123.13007127249938,
 'Kareem Hunt': 451.17925798034497,
 "Ke'Shawn Vaughn": 87.0548917774998,
 'Keith Smith': 9.665684346279148,
 'Kene Nwangwu': 13.153850420266313,
 'Kenny Gainwell': 363.87424310177977,
 'Kenyan Drake': 0.033163208997677884,
 'Khalil Herbert': 611.1987219410208,
 'Kyle Juszczyk': 9.805805617099967,
 'Latavius Murray': 374.1442146475435,
 "Le'Veon Bell": 114.81586943369737,
 'Leonard Fournette': 312.0522685714874,
 'Malcolm Brown': 199.57299431826672,
 'Mark Ingram': 515.2112675898637,
 'Marlon Mack': 315.67658475051786,
 'Matt Breida': 74.10729453490218,
 'Melvin Gordon': 148.30642842652898,
 'Michael Burton': 14.351324790532232,
 'Michael Carter': -216.03863737770325,
 'Mike Boone': 43.26113940400999,
 'Mike Davis': 286.62685575118405,
 'Miles Sanders': 583.8952245985834,
 'Myles Gaskin': -304.8829787790709,
 'Najee Harris': 1080.522231677649,
 'Nick Bawden': 4.0000000001832365,
 'Nick Chubb': 807.7289734166084,
 'Nyheim Hines': -44.62837804791912,
 'Patrick Laird': -159.83360615033388,
 'Patrick Ricard': 3.640033339594544,
 'Patrick Taylor': 140.54286850435727,
 'Peyton Barber': 236.09618914408702,
 'Phillip Lindsay': -473.2240031324136,
 'Qadree Ollison': 98.02565189782082,
 'Raheem Mostert': 664.551550035365,
 'Rashaad Penny': 293.43590410849384,
 'Reggie Bonnafon': 26.564470312609572,
 'Reggie Gilliam': 0.7835477695469812,
 'Rex Burkhead': 369.7701004282035,
 'Rhamondre Stevenson': 619.0229823331919,
 'Ronald Jones II': 110.85183164676616,
 'Royce Freeman': 282.132491779681,
 'Ryan Nall': 2.9982159618544313,
 'Salvon Ahmed': 83.9332750017297,
 'Samaje Perine': 238.00404373312688,
 'Saquon Barkley': 761.280882229909,
 'Sony Michel': 624.6267553688294,
 'Tevin Coleman': 357.2884058130006,
 'Tony Jones': 89.81875469665546,
 'Tony Pollard': 940.7139756895701,
 'Travis Homer': 129.65348208670207,
 'Trayveon Williams': 90.6865094311005,
 'Trey Sermon': 159.70496310318543,
 'Ty Johnson': 73.57797920734104,
 'Wayne Gallman': 104.08444769928474,
 'Zack Moss': 1059.1030689720283}

In [21]:
Predictions24 = pd.DataFrame(list(predictions_2024.items()), columns=['Name', 'Rush Yards'])

In [22]:
Predictions24

                  Name   Rush Yards
0            AJ Dillon   555.485428
1          Aaron Jones   736.186847
2        Adam Prentice    16.772042
3      Adrian Peterson -1102.744202
4          Alec Ingold     2.890765
..                 ...          ...
126  Trayveon Williams    90.686509
127        Trey Sermon   159.704963
128         Ty Johnson    73.577979
129      Wayne Gallman   104.084448
130          Zack Moss  1059.103069

[131 rows x 2 columns]

In [23]:
Predictions24['Year'] = 2024

In [24]:
Predictions24.reset_index(inplace=True)
Predictions24.set_index('Year', inplace = True)
Predictions24.index = pd.to_datetime(Predictions24.index, format='%Y')

In [25]:
Predictions24.reset_index(inplace=True)

In [26]:
Predictions24

          Year  index               Name   Rush Yards
0   2024-01-01      0          AJ Dillon   555.485428
1   2024-01-01      1        Aaron Jones   736.186847
2   2024-01-01      2      Adam Prentice    16.772042
3   2024-01-01      3    Adrian Peterson -1102.744202
4   2024-01-01      4        Alec Ingold     2.890765
..         ...    ...                ...          ...
126 2024-01-01    126  Trayveon Williams    90.686509
127 2024-01-01    127        Trey Sermon   159.704963
128 2024-01-01    128         Ty Johnson    73.577979
129 2024-01-01    129      Wayne Gallman   104.084448
130 2024-01-01    130          Zack Moss  1059.103069

[131 rows x 4 columns]

In [27]:
Predictions24.drop(columns = ['index'])

          Year               Name   Rush Yards
0   2024-01-01          AJ Dillon   555.485428
1   2024-01-01        Aaron Jones   736.186847
2   2024-01-01      Adam Prentice    16.772042
3   2024-01-01    Adrian Peterson -1102.744202
4   2024-01-01        Alec Ingold     2.890765
..         ...                ...          ...
126 2024-01-01  Trayveon Williams    90.686509
127 2024-01-01        Trey Sermon   159.704963
128 2024-01-01         Ty Johnson    73.577979
129 2024-01-01      Wayne Gallman   104.084448
130 2024-01-01          Zack Moss  1059.103069

[131 rows x 3 columns]

In [28]:
Predictions24 = Predictions24.drop(columns = ['index'])

In [29]:
Predictions24

          Year               Name   Rush Yards
0   2024-01-01          AJ Dillon   555.485428
1   2024-01-01        Aaron Jones   736.186847
2   2024-01-01      Adam Prentice    16.772042
3   2024-01-01    Adrian Peterson -1102.744202
4   2024-01-01        Alec Ingold     2.890765
..         ...                ...          ...
126 2024-01-01  Trayveon Williams    90.686509
127 2024-01-01        Trey Sermon   159.704963
128 2024-01-01         Ty Johnson    73.577979
129 2024-01-01      Wayne Gallman   104.084448
130 2024-01-01          Zack Moss  1059.103069

[131 rows x 3 columns]

In [30]:
RB

,Name,Fantasy Points,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs,Style,RunningSkill
Year,,,,,,,,,,,
2020-01-01,AJ Dillon,36.0,46,242,0,2,2.0,21.0,0.0,TraditionalRB,Backup
2021-01-01,AJ Dillon,172.0,187,803,1,5,34.0,313.0,2.0,TraditionalRB,RB2
2022-01-01,AJ Dillon,157.0,186,770,0,7,28.0,206.0,0.0,TraditionalRB,RB2
2023-01-01,AJ Dillon,108.0,178,613,0,2,22.0,223.0,0.0,TraditionalRB,RB2
2019-01-01,Aaron Jones,304.0,236,1084,2,16,49.0,474.0,3.0,ReceivngBack,RB1
...,...,...,...,...,...,...,...,...,...,...,...
2023-01-01,Zack Moss,159.0,183,794,0,5,27.0,192.0,2.0,TraditionalRB,RB2
2022-01-01,Zamir White,4.0,17,70,0,0,0.0,0.0,0.0,TraditionalRB,Backup
2023-01-01,Zamir White,67.0,104,451,1,1,15.0,98.0,0.0,TraditionalRB,RB2
2022-01-01,Zonovan Knight,54.0,85,300,0,1,13.0,100.0,0.0,TraditionalRB,Backup
2023-01-01,Zonovan Knight,2.0,3,13,0,0,1.0,8.0,0.0,TraditionalRB,Backup

In [31]:
RushingYards = RB.drop(columns = ['Receptions','Receiving TDs', 'Receiving Yards','Rush Attempts','Fumbles','RushTDs'])

In [32]:
RushingYards.reset_index(inplace=True)

In [33]:
RushingYards

,Year,Name,Fantasy Points,Rush Yards,Style,RunningSkill
0,2020-01-01,AJ Dillon,36.0,242,TraditionalRB,Backup
1,2021-01-01,AJ Dillon,172.0,803,TraditionalRB,RB2
2,2022-01-01,AJ Dillon,157.0,770,TraditionalRB,RB2
3,2023-01-01,AJ Dillon,108.0,613,TraditionalRB,RB2
4,2019-01-01,Aaron Jones,304.0,1084,ReceivngBack,RB1
...,...,...,...,...,...,...
787,2023-01-01,Zack Moss,159.0,794,TraditionalRB,RB2
788,2022-01-01,Zamir White,4.0,70,TraditionalRB,Backup
789,2023-01-01,Zamir White,67.0,451,TraditionalRB,RB2
790,2022-01-01,Zonovan Knight,54.0,300,TraditionalRB,Backup
791,2023-01-01,Zonovan Knight,2.0,13,TraditionalRB,Backup

In [34]:
concatenated_df = pd.concat([RushingYards, Predictions24])

In [35]:
concatenated_df

,Year,Name,Fantasy Points,Rush Yards,Style,RunningSkill
0,2020-01-01,AJ Dillon,36.0,242.000000,TraditionalRB,Backup
1,2021-01-01,AJ Dillon,172.0,803.000000,TraditionalRB,RB2
2,2022-01-01,AJ Dillon,157.0,770.000000,TraditionalRB,RB2
3,2023-01-01,AJ Dillon,108.0,613.000000,TraditionalRB,RB2
4,2019-01-01,Aaron Jones,304.0,1084.000000,ReceivngBack,RB1
...,...,...,...,...,...,...
126,2024-01-01,Trayveon Williams,NaN,90.686509,NaN,NaN
127,2024-01-01,Trey Sermon,NaN,159.704963,NaN,NaN
128,2024-01-01,Ty Johnson,NaN,73.577979,NaN,NaN
129,2024-01-01,Wayne Gallman,NaN,104.084448,NaN,NaN
130,2024-01-01,Zack Moss,NaN,1059.103069,NaN,NaN

In [36]:
concatenated_df.loc[(concatenated_df['Rush Yards'] > 400) & (concatenated_df['Rush Yards'] < 900), 'RunningSkill'] = 'RB2'
concatenated_df.loc[(concatenated_df['Rush Yards'] >= 900) , 'RunningSkill'] = 'RB1'
concatenated_df.loc[(concatenated_df['Rush Yards'] <= 400), 'RunningSkill'] = 'Backup'

In [37]:
concatenated_df

,Year,Name,Fantasy Points,Rush Yards,Style,RunningSkill
0,2020-01-01,AJ Dillon,36.0,242.000000,TraditionalRB,Backup
1,2021-01-01,AJ Dillon,172.0,803.000000,TraditionalRB,RB2
2,2022-01-01,AJ Dillon,157.0,770.000000,TraditionalRB,RB2
3,2023-01-01,AJ Dillon,108.0,613.000000,TraditionalRB,RB2
4,2019-01-01,Aaron Jones,304.0,1084.000000,ReceivngBack,RB1
...,...,...,...,...,...,...
126,2024-01-01,Trayveon Williams,NaN,90.686509,NaN,Backup
127,2024-01-01,Trey Sermon,NaN,159.704963,NaN,Backup
128,2024-01-01,Ty Johnson,NaN,73.577979,NaN,Backup
129,2024-01-01,Wayne Gallman,NaN,104.084448,NaN,Backup
130,2024-01-01,Zack Moss,NaN,1059.103069,NaN,RB1

In [38]:
RushingYards2 = concatenated_df.sort_values(by=['Name','Year'], ascending=True)

In [39]:
RushingYards2

,Year,Name,Fantasy Points,Rush Yards,Style,RunningSkill
0,2020-01-01,AJ Dillon,36.0,242.000000,TraditionalRB,Backup
1,2021-01-01,AJ Dillon,172.0,803.000000,TraditionalRB,RB2
2,2022-01-01,AJ Dillon,157.0,770.000000,TraditionalRB,RB2
3,2023-01-01,AJ Dillon,108.0,613.000000,TraditionalRB,RB2
0,2024-01-01,AJ Dillon,NaN,555.485428,NaN,RB2
...,...,...,...,...,...,...
130,2024-01-01,Zack Moss,NaN,1059.103069,NaN,RB1
788,2022-01-01,Zamir White,4.0,70.000000,TraditionalRB,Backup
789,2023-01-01,Zamir White,67.0,451.000000,TraditionalRB,RB2
790,2022-01-01,Zonovan Knight,54.0,300.000000,TraditionalRB,Backup
791,2023-01-01,Zonovan Knight,2.0,13.000000,TraditionalRB,Backup

In [40]:
RushingYards2['Style'].fillna(method='ffill', inplace=True)

In [41]:
RushingYards2

,Year,Name,Fantasy Points,Rush Yards,Style,RunningSkill
0,2020-01-01,AJ Dillon,36.0,242.000000,TraditionalRB,Backup
1,2021-01-01,AJ Dillon,172.0,803.000000,TraditionalRB,RB2
2,2022-01-01,AJ Dillon,157.0,770.000000,TraditionalRB,RB2
3,2023-01-01,AJ Dillon,108.0,613.000000,TraditionalRB,RB2
0,2024-01-01,AJ Dillon,NaN,555.485428,TraditionalRB,RB2
...,...,...,...,...,...,...
130,2024-01-01,Zack Moss,NaN,1059.103069,TraditionalRB,RB1
788,2022-01-01,Zamir White,4.0,70.000000,TraditionalRB,Backup
789,2023-01-01,Zamir White,67.0,451.000000,TraditionalRB,RB2
790,2022-01-01,Zonovan Knight,54.0,300.000000,TraditionalRB,Backup
791,2023-01-01,Zonovan Knight,2.0,13.000000,TraditionalRB,Backup

In [42]:
X = RB.drop(['Fantasy Points'], axis=1)
y = RB['Fantasy Points']


numeric_features = ['Rush Yards']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
      
    ]
)


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


X_train_subset = X_train[X_train.index.year < 2023]
y_train_subset = y_train[y_train.index.year < 2023]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2023]
y_test_subset = y_test[y_test.index.year == 2023]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 518.73730658452
R-squared: 0.9183606405113433

In [43]:
# Filter 'WR_merged' to keep only the most recent prediction for each player
latest_predictions = RushingYards2.groupby('Name')['Rush Yards'].last().reset_index()

# Preprocess the data for prediction
X_2024 = latest_predictions[['Rush Yards']]

# Make predictions for fantasy points in 2024
y_pred_2024 = pipeline.predict(X_2024)

# Combine player names and their corresponding predicted fantasy points
player_predictions = pd.DataFrame({
    'Player': latest_predictions['Name'],
    'Predicted_Fantasy_Points_2024': y_pred_2024.round(2)  # Round predictions to 2 decimal places
})

# Print the predicted fantasy points for 2024
print(player_predictions)

              Player  Predicted_Fantasy_Points_2024
0          AJ Dillon                         121.34
1        Aaron Jones                         157.99
2      Adam Prentice                          12.08
3     Adrian Killins                           6.25
4    Adrian Peterson                        -214.97
..               ...                            ...
288        Zach Line                          12.74
289      Zach Zenner                           8.27
290        Zack Moss                         223.48
291      Zamir White                         100.15
292   Zonovan Knight                          11.32

[293 rows x 2 columns]

In [44]:
player_predictions

              Player  Predicted_Fantasy_Points_2024
0          AJ Dillon                         121.34
1        Aaron Jones                         157.99
2      Adam Prentice                          12.08
3     Adrian Killins                           6.25
4    Adrian Peterson                        -214.97
..               ...                            ...
288        Zach Line                          12.74
289      Zach Zenner                           8.27
290        Zack Moss                         223.48
291      Zamir White                         100.15
292   Zonovan Knight                          11.32

[293 rows x 2 columns]

In [45]:
DataFrame = pd.read_csv('../Data.csv')
RB2 = DataFrame[DataFrame['Position'] == 'RB']
RB2 = RB2.drop(columns = ['PassingYards','PassingTDs','Ints'])
RB2 = RB2.drop(columns = ['Week','Position','Game','Unnamed: 0'])
RB2 = RB2.groupby(['Name','Year']).sum()
RB2.reset_index(inplace=True)

In [46]:
RB2

,Name,Year,Fantasy Points,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,AJ Dillon,2020,36.0,46,242,0,2,2.0,21.0,0.0
1,AJ Dillon,2021,172.0,187,803,1,5,34.0,313.0,2.0
2,AJ Dillon,2022,157.0,186,770,0,7,28.0,206.0,0.0
3,AJ Dillon,2023,108.0,178,613,0,2,22.0,223.0,0.0
4,Aaron Jones,2019,304.0,236,1084,2,16,49.0,474.0,3.0
...,...,...,...,...,...,...,...,...,...,...
787,Zack Moss,2023,159.0,183,794,0,5,27.0,192.0,2.0
788,Zamir White,2022,4.0,17,70,0,0,0.0,0.0,0.0
789,Zamir White,2023,67.0,104,451,1,1,15.0,98.0,0.0
790,Zonovan Knight,2022,54.0,85,300,0,1,13.0,100.0,0.0
791,Zonovan Knight,2023,2.0,3,13,0,0,1.0,8.0,0.0

In [47]:
name_fantasy_dict = {}

# Iterate over the rows of the DataFrame
for index, row in RB2.iterrows():
    name = row['Name']
    year = row['Year']
    fantasy_points = row['Fantasy Points']
    
    if name not in name_fantasy_dict:  # If the player is not already in the dictionary
        name_fantasy_dict[name] = [fantasy_points if y == year else 0 for y in range(2019, 2024)]
    else:
        # If the player is already in the dictionary, update the corresponding value list
        name_fantasy_dict[name][year - 2019] = fantasy_points

# Print the resulting dictionary
print(name_fantasy_dict)

{'AJ Dillon': [0, 36.0, 172.0, 157.0, 108.0], 'Aaron Jones': [304.0, 247.0, 218.0, 237.0, 127.0], 'Adam Prentice': [0, 0, 4.0, 3.0, 1.0], 'Adrian Killins': [0, 1.0, 0, 0, 0], 'Adrian Peterson': [135.0, 114.0, 25.0, 0, 0], 'Alec Ingold': [15.0, 26.0, 22.0, 34.0, 22.0], 'Alex Armah': [8.0, 6.0, 8.0, 0, 4.0], 'Alex Collins': [0, 19.0, 62.0, 0, 0], 'Alexander Horvath': [0, 0, 0, 17.0, 0], 'Alexander Mattison': [61.0, 79.0, 118.0, 77.0, 124.0], 'Alfred Morris': [0.0, 33.0, 0, 0, 0], 'Alvin Kamara': [237.0, 364.0, 224.0, 202.0, 223.0], 'Ameer Abdullah': [35.0, 27.0, 80.0, 47.0, 32.0], 'Andrew Beck': [21.0, 0, 0, 11.0, 30.0], 'Andy Janovich': [13.0, 3.0, 11.0, 0, 0], 'Anthony McFarland': [0, 14.0, 2.0, 6.0, 3.0], 'Anthony Sherman': [3.0, 7.0, 0, 0, 0], 'Antonio Gibson': [0, 194.0, 220.0, 152.0, 114.0], 'Antonio Williams': [0, 21.0, 0, 0, 0], 'Artavis Pierce': [0, 8.0, 0, 0, 0], 'Austin Ekeler': [295.0, 156.0, 331.0, 358.0, 174.0], 'Austin Walter': [0, 3.0, 16.0, 0, 0], 'Avery Williams': [0, 0, 0, 28.0, 0], 'Benjamin Snell': [54.0, 70.0, 9.0, 17.0, 0], 'Bijan Robinson': [0, 0, 0, 0, 237.0], 'Bilal Powell': [26.0, 0, 0, 0, 0], 'Bo Scarbrough': [41.0, 3.0, 0, 0, 0], 'Boston Scott': [91.0, 83.0, 94.0, 39.0, 11.0], 'Brandon Bolden': [47.0, 0, 114.0, 23.0, 10.0], 'Breece Hall': [0, 0, 0, 111.0, 274.0], 'Brian Hill': [62.0, 83.0, 0, 0, 0], 'Brian Robinson': [0, 0, 0, 106.0, 189.0], 'Bruce Miller': [0, 1.0, 0, 0, 0], 'C.J. Anderson': [3.0, 0, 0, 0, 0], 'C.J. Ham': [34.0, 23.0, 27.0, 27.0, 7.0], 'C.J. Prosise': [24.0, 12.0, 0, 0, 0], 'Caleb Huntley': [0, 0, 0, 40.0, 0], 'Cam Akers': [0, 96.0, 4.0, 136.0, 41.0], 'Carlos Hyde': [146.0, 76.0, 42.0, 0, 0], 'Cartavious Bigsby': [0, 0, 0, 0, 20.0], 'Chandler Cox': [0, 2.0, 0, 0, 0], 'Chase Brown': [0, 0, 0, 0, 48.0], 'Chase Edmonds': [75.0, 152.0, 133.0, 65.0, 33.0], 'Chris Carson': [225.0, 178.0, 48.0, 0, 0], 'Chris Evans': [0, 0, 44.0, 11.0, 2.0], 'Chris Myarick': [0, 0, 10.0, 18.0, 0], 'Chris Thompson': [84.0, 38.0, 0, 0, 0], 'Christian McCaffrey': [456.0, 86.0, 121.0, 341.0, 378.0], 'Christopher Brooks': [0, 0, 0, 0, 9.0], 'Christopher Rodriguez': [0, 0, 0, 0, 34.0], 'Chuba Hubbard': [0, 0, 127.0, 82.0, 165.0], 'Clyde Edwards-Helaire': [0, 165.0, 111.0, 93.0, 58.0], 'Cordarrelle Patterson': [24.0, 51.0, 222.0, 141.0, 30.0], 'Corey Clement': [-2.0, 15.0, 26.0, 20.0, 0], 'Craig Reynolds': [0, 1.0, 31.0, 26.0, 27.0], 'Cullen Gillaspia': [0, 1.0, 0, 0, 0], "D'Andre Swift": [0, 181.0, 199.0, 180.0, 189.0], "D'Ernest Johnson": [13.0, 17.0, 94.0, 4.0, 26.0], "D'Onta Foreman": [0, 14.0, 86.0, 122.0, 87.0], 'D.J. Foster': [0, 1.0, 0, 0, 0], 'Dalvin Cook': [282.0, 330.0, 198.0, 227.0, 33.0], 'Dalyn Dawkins': [2.0, 0, 0, 0, 0], 'Damarea Crockett': [0, 0, 0.0, 0, 0], 'Dameon Pierce': [0, 0, 0, 155.0, 67.0], 'Damien Harris': [1.0, 87.0, 204.0, 82.0, 16.0], 'Damien Williams': [132.0, 0, 56.0, 0.0, 5.0], 'Dan Vitale': [14.0, 0, 0, 0, 0], 'Dare Ogunbowale': [70.0, 26.0, 43.0, 42.0, 7.0], 'Darrel Williams': [63.0, 45.0, 185.0, 16.0, 0], 'Darrell Henderson': [17.0, 119.0, 152.0, 66.0, 40.0], 'Darren Sproles': [13.0, 0, 0, 0, 0], 'Darrynton Evans': [0, 14.0, 3.0, 9.0, 25.0], 'Darwin Thompson': [27.0, 32.0, 0, 0, 0], 'David Johnson': [132.0, 170.0, 70.0, 8.0, 0], 'David Montgomery': [160.0, 252.0, 185.0, 168.0, 199.0], "De'Lance Turner": [0.0, 0, 0, 0, 0], "De'Von Achane": [0, 0, 0, 0, 184.0], 'DeAndre Washington': [107.0, 14.0, 0, 0, 0], 'DeeJay Dallas': [0, 50.0, 53.0, 40.0, 7.0], 'Demetric Felton': [0, 0, 46.0, 2.0, 0], 'Deon Jackson': [0, 0, 8.0, 79.0, 5.0], 'Derek Watt': [11.0, 0, 3.0, 17.0, 0], 'Derrick Gore': [0, 0, 50.0, 0, 2.0], 'Derrick Henry': [284.0, 323.0, 189.0, 293.0, 238.0], 'Derrius Guice': [53.0, 0, 0, 0, 0], 'Deuce Vaughn': [0, 0, 0, 0, 11.0], 'Devin Singletary': [137.0, 133.0, 182.0, 165.0, 158.0], 'Devine Ozigbo': [7.0, 12.0, 1.0, 1.0, 1.0], 'Devonta Freeman': [187.0, 34.0, 134.0, 0, 0], 'Devontae Booker': [10.0, 75.0, 128.0, 0, 0], 'Dexter Williams': [0.0, 0.0, 0, 0, 0], 'Dion Lewis': [56.0, 51.0, 0, 0, 0], 'Dontrell Hilliard': [33.0, 4.0, 70.0, 71.0, 0], 'Duke Johnson': [143.0, 79.0, 54.0, 0.0, 0], 'Dwayne Washington': [6.0, 0.0, 2.0, 3.0, 0], 'Elijah Dotson': [0, 0, 0, 0, 3.0], 'Elijah Mitchell': [0, 0, 157.0, 40.0, 45.0], 'Elijhaa Penny': [4.0, 3.0, 31.0, 0, 0], 'Emanuel Wilson': [0, 0, 0, 0, 10.0], 'Emari Demercado': [0, 0, 0, 0, 66.0], 'Eno Benjamin': [0, 0, 24.0, 80.0, 0], 'Eric Gray': [0, 0, 0, 0, 9.0], 'Evan Hull': [0, 0, 0, 0, 1.0], 'Ezekiel Elliott': [300.0, 216.0, 241.0, 176.0, 161.0], 'Frank Gore': [84.0, 92.0, 0, 0, 0], 'Gabe Nabers': [0, 17.0, 4.0, 0, 0], 'Gary Brightwell': [0, 0, 1.0, 25.0, 9.0], 'Giovani Bernard': [59.0, 146.0, 54.0, 4.0, 0], 'Godwin Igwebuike': [0, 0, 26.0, 1.0, 0], 'Greg Howell': [0.0, 7.0, 1.0, 0, 0], 'Gus Edwards': [83.0, 120.0, 0, 56.0, 179.0], 'Hassan Haskins': [0, 0, 0, 21.0, 0], 'Hunter Luepke': [0, 0, 0, 0, 10.0], 'Isaiah Spiller': [0, 0, 0, 7.0, 15.0], 'Isiah Pacheco': [0, 0, 0, 125.0, 206.0], 'Israel Abanikanda': [0, 0, 0, 0, 14.0], 'Ito Smith': [32.0, 48.0, 6.0, 0, 0], 'J.D. McKissic': [74.0, 180.0, 120.0, 50.0, 0], 'J.J. Taylor': [0, 10.0, 18.0, 1.0, 0], 'J.K. Dobbins': [0, 159.0, 0, 77.0, 11.0], 'JaMycal Hasty': [0, 26.0, 44.0, 63.0, 0], 'JaQuan Hardy': [0, 0, 8.0, 0, 0], 'Jacques Patrick': [0, 0, 1.0, 0, 0], 'Jahmyr Gibbs': [0, 0, 0, 0, 232.0], 'Jake Funk': [0, 0, 0.0, 0, 3.0], 'Jakob Johnson': [1.0, 16.0, 7.0, 5.0, 2.0], 'Jaleel McLaughlin': [0, 0, 0, 0, 95.0], 'Jalen Richard': [70.0, 42.0, 17.0, 0, 0], 'Jamaal Williams': [135.0, 118.0, 110.0, 217.0, 49.0], 'James Conner': [140.0, 153.0, 247.0, 187.0, 191.0], 'James Cook': [0, 0, 0, 95.0, 219.0], 'James Develin': [0.0, 0, 0, 0, 0], 'James Robinson': [0, 237.0, 162.0, 82.0, 1.0], 'James White': [187.0, 108.0, 29.0, 0, 0], 'Jaret Patterson': [0, 0, 49.0, 7.0, 0], 'Jashaun Corbin': [0, 0, 0, 0, 4.0], 'Jason Cabinda': [0, 2.0, 12.0, 1.0, 0.0], 'Jason Huntley': [0, 2.0, 5.0, 0, 0], 'Javonte Williams': [0, 0, 194.0, 40.0, 169.0], 'Javorius Allen': [9.0, 0, 0, 0, 0], 'Jay Ajayi': [1.0, 0, 0, 0, 0], 'Jaylen Samuels': [94.0, 13.0, 4.0, 0, 0], 'Jaylen Warren': [0, 0, 0, 80.0, 182.0], 'Jeffery Wilson': [43.0, 138.0, 47.0, 150.0, 36.0], 'Jeremy McNichols': [0, 36.0, 65.0, 0, 0], 'Jerick McKinnon': [0, 118.0, 31.0, 187.0, 77.0], 'Jermar Jefferson': [0, 0, 23.0, 0, 0], 'Jerome Ford': [0, 0, 0, 0.0, 198.0], 'Joe Mixon': [214.0, 95.0, 277.0, 229.0, 249.0], 'John Kelly': [0.0, 0, 1.0, 0, 0], 'Johnny Stanton': [0, 0, 8.0, 0, 0], 'Jon Hilliman': [9.0, 0, 0, 0, 0], 'Jonathan Taylor': [0, 242.0, 362.0, 142.0, 146.0], 'Jonathan Ward': [0, 8.0, 6.0, 4.0, 1.0], 'Jonathan Williams': [38.0, 5.0, 16.0, 22.0, 0.0], 'Jordan Howard': [104.0, 27.0, 58.0, 0.0, 0], 'Jordan Mason': [0, 0, 0, 28.0, 41.0], 'Jordan Scarlett': [0.0, 0, 0, 0, 0], 'Jordan Wilkins': [46.0, 53.0, 0, 12.0, 0], 'Josh Adams': [0.0, 33.0, 0, 0, 0], 'Josh Ferguson': [0.0, 0, 0, 0, 0], 'Josh Jacobs': [184.0, 217.0, 213.0, 312.0, 171.0], 'Joshua Kelley': [0, 74.0, 12.0, 55.0, 53.0], 'Julius Chestnut': [0, 0, 0, 7.0, 0], 'Justice Hill': [39.0, 10.0, 0, 35.0, 102.0], 'Justin Jackson': [25.0, 60.0, 79.0, 43.0, 0], 'Kalen Ballage': [43.0, 85.0, 5.0, 0, 0], 'Kareem Hunt': [94.0, 206.0, 104.0, 112.0, 110.0], "Ke'Shawn Vaughn": [0, 22.0, 33.0, 7.0, 3.0], 'Keaontay Ingram': [0, 0, 0, 14.0, 10.0], 'Keaton Mitchell': [0, 0, 0, 0, 64.0], 'Keith Smith': [2.0, 15.0, 13.0, 1.0, 5.0], 'Kendre Miller': [0, 0, 0, 0, 39.0], 'Kene Nwangwu': [0, 0, 7.0, 4.0, 0.0], 'Kenjon Barner': [7.0, 0, 0.0, 0, 0], 'Kenneth Walker': [0, 0, 0, 191.0, 187.0], 'Kenny Gainwell': [0, 0, 113.0, 75.0, 88.0], 'Kenyan Drake': [203.0, 180.0, 93.0, 94.0, 4.0], 'Kerrith Whyte': [12.0, 0, 0, 0, 0], 'Kerryon Johnson': [80.0, 63.0, 0, 0, 0], 'Kevin Harris': [0, 0, 0, 9.0, 19.0], 'Khalil Herbert': [0, 0, 72.0, 111.0, 102.0], 'Khari Blasingame': [8.0, 6.0, 1.0, 0, 5.0], 'Kyle Juszczyk': [47.0, 71.0, 65.0, 47.0, 34.0], 'Kylin Hill': [0, 0, 2.0, 0.0, 0], 'Kyren Williams': [0, 0, 0, 23.0, 248.0], 'Lamar Miller': [0, 2.0, 0, 0, 0], 'Lamical Perine': [0, 45.0, 2.0, 0, 13.0], 'Larry Rountree': [0, 0, 14.0, 4.0, 0], 'Latavius Murray': [144.0, 122.0, 96.0, 144.0, 71.0], "Le'Veon Bell": [204.0, 68.0, 35.0, 0, 0], 'LeSean McCoy': [112.0, 25.0, 0, 0, 0], 'LeVante Bellamy': [0, 2.0, 0, 0, 0], 'Leonard Fournette': [249.0, 122.0, 242.0, 212.0, 4.0], 'Malcolm Brown': [55.0, 99.0, 20.0, 19.0, 0], 'Malcolm Perry': [0, 22.0, 0, 0, 0], 'Malik Davis': [0, 0, 0, 29.0, 0], 'Mark Ingram': [232.0, 47.0, 100.0, 46.0, 0], 'Mark Walton': [39.0, 0, 0, 0, 0], 'Marlon Mack': [170.0, 8.0, 10.0, 34.0, 0], 'Marshawn Lynch': [9.0, 0, 0, 0, 0], 'Matt Breida': [94.0, 35.0, 39.0, 47.0, 39.0], 'Mekhi Sargent': [0, 0, 0.0, 0, 0], 'Melvin Gordon': [173.0, 191.0, 187.0, 78.0, 19.0], 'Michael Burton': [0, 6.0, 12.0, 2.0, 5.0], 'Michael Carter': [0, 0, 140.0, 114.0, 49.0], 'Mike Boone': [46.0, 11.0, 6.0, 23.0, 10.0], 'Mike Davis': [9.0, 197.0, 130.0, 3.0, 0], 'Miles Sanders': [207.0, 163.0, 110.0, 209.0, 80.0], 'Myles Gaskin': [27.0, 158.0, 160.0, 7.0, 0], 'Najee Harris': [0, 0, 285.0, 213.0, 185.0], 'Nate Cottrell': [0, 0, 0.0, 0, 0], 'Nate McCrary': [0, 0, 0.0, 0, 0], 'Nick Bawden': [5.0, 0, 3.0, 0, 9.0], 'Nick Chubb': [245.0, 200.0, 204.0, 269.0, 22.0], 'Nyheim Hines': [96.0, 181.0, 101.0, 63.0, 0], 'Patrick DiMarco': [7.0, 0, 0, 0, 0], 'Patrick Laird': [61.0, 16.0, 4.0, 0, 0], 'Patrick Ricard': [16.0, 16.0, 18.0, 16.0, 15.0], 'Patrick Taylor': [0, 0, 15.0, 4.0, 26.0], 'Paul Perkins': [2.0, 0, 0, 0, 0], 'Peyton Barber': [107.0, 47.0, 46.0, 0, 0], 'Phillip Lindsay': [185.0, 60.0, 38.0, 13.0, 0], 'Pierre Strong': [0, 0, 0, 26.0, 38.0], 'Qadree Ollison': [28.0, 0.0, 16.0, 0, 0], 'Rachaad White': [0, 0, 0, 128.0, 256.0], 'Raheem Blackshear': [0, 0, 0, 42.0, 11.0], 'Raheem Mostert': [157.0, 95.0, 2.0, 158.0, 256.0], 'Rashaad Penny': [71.0, 1.0, 114.0, 49.0, 2.0], 'Reggie Bonnafon': [24.0, 15.0, 3.0, 0.0, 0], 'Reggie Gilliam': [0, 9.0, 3.0, 19.0, 1.0], 'Rex Burkhead': [91.0, 99.0, 96.0, 68.0, 0], 'Rhamondre Stevenson': [0, 0, 106.0, 236.0, 137.0], 'Ricky Ortiz': [1.0, 0, 0, 0, 0], 'Rico Dowdle': [0, 2.0, 0, 0, 78.0], 'Rodney Smith': [0, 32.0, 9.0, 0, 0], 'Ronald Jones II': [156.0, 176.0, 71.0, 14.0, 0], 'Ronnie Rivers': [0, 0, 0, 9.0, 17.0], 'Roosevelt Nix': [2.0, 0, 0, 0, 0], 'Roschon Johnson': [0, 0, 0, 0, 92.0], 'Royce Freeman': [130.0, 31.0, 28.0, 17.0, 42.0], 'Ryan Nall': [0.0, 19.0, 1.0, 0, 0], 'Ryquell Armstead': [45.0, 0, 11.0, 0, 0], 'Salvon Ahmed': [0, 64.0, 29.0, 12.0, 38.0], 'Samaje Perine': [1.0, 59.0, 73.0, 129.0, 110.0], 'Saquon Barkley': [233.0, 14.0, 142.0, 271.0, 214.0], 'Scottie Phillips': [0, 1.0, 3.0, 0, 0], 'Sean Tucker': [0, 0, 0, 0, 3.0], 'Senorise Perry': [1.0, 0.0, 0, 0, 0], 'Snoop Conner': [0, 0, 0, 8.0, 0], 'Sony Michel': [145.0, 69.0, 137.0, 19.0, 0], 'Spencer Brown': [0, 0, 0, 6.0, 0], 'Spencer Ware': [11.0, 0, 0, 0, 0], 'T.J. Logan': [3.0, 0, 0, 0, 0], 'T.J. Yeldon': [27.0, 15.0, 0, 0, 0], 'Taiwan Jones': [5.0, 0, 0, -1.0, 0], 'Tarik Cohen': [146.0, 16.0, 0, 0, 0], 'Tevin Coleman': [126.0, 11.0, 43.0, 21.0, 0], 'Theo Riddick': [0, 10.0, 0, 0, 0], 'Todd Gurley': [211.0, 151.0, 0, 0, 0], 'Tony Brooks-James': [1.0, 0.0, 0, 0, 0], 'Tony Jones': [0, 1.0, 18.0, 8.0, 30.0], 'Tony Pollard': [82.0, 109.0, 145.0, 237.0, 210.0], 'Tra Carson': [9.0, 0, 0, 0, 0], 'Travis Etienne': [0, 0, 0, 194.0, 266.0], 'Travis Homer': [25.0, 28.0, 48.0, 37.0, 0], 'Trayveon Williams': [0, 19.0, 5.0, 5.0, 11.0], 'Trenton Cannon': [0, 6.0, -1.0, 0, 0], 'Trestan Ebner': [0, 0, 0, 5.0, 0], 'Trey Edmunds': [17.0, 0, 0, 0, 0], 'Trey Ragas': [0, 0, 2.0, 0, 0], 'Trey Sermon': [0, 0, 25.0, 1.0, 16.0], 'Troy Hairston': [0, 0, 0, 5.0, 0], 'Troymaine Pope': [10.0, 17.0, 0, 0, 0], 'Ty Chandler': [0, 0, 0, 2.0, 91.0], 'Ty Johnson': [50.0, 57.0, 109.0, 36.0, 27.0], "Ty'Son Williams": [0, 0, 37.0, 1.0, 0], 'Tyjae Spears': [0, 0, 0, 0, 137.0], 'Tyler Allgeier': [0, 0, 0, 152.0, 127.0], 'Tyler Badie': [0, 0, 0, 9.0, 0], 'Tyler Ervin': [3.0, 20.0, 0, 0, 0], 'Tyler Goodson': [0, 0, 0, 0, 16.0], 'Tyrion Davis-Price': [0, 0, 0, 8.0, 2.0], 'Wayne Gallman': [46.0, 125.0, 11.0, 0, 0], 'Wendell Smallwood': [17.0, 0, 8.0, 0, 0], 'Wes Hills': [16.0, 0, 0, 0, 0], 'Zach Charbonnet': [0, 0, 0, 0, 94.0], 'Zach Evans': [0, 0, 0, 0, 1.0], 'Zach Line': [8.0, 0, 0, 0, 0], 'Zach Zenner': [3.0, 0, 0, 0, 0], 'Zack Moss': [0, 93.0, 95.0, 57.0, 159.0], 'Zamir White': [0, 0, 0, 4.0, 67.0], 'Zonovan Knight': [0, 0, 0, 54.0, 2.0]}

In [48]:
for index, row in player_predictions.iterrows():
    player = row['Player']
    predicted_points = row['Predicted_Fantasy_Points_2024']
    if player in name_fantasy_dict:
        name_fantasy_dict[player].append(predicted_points)
   

print(name_fantasy_dict)

{'AJ Dillon': [0, 36.0, 172.0, 157.0, 108.0, 121.34], 'Aaron Jones': [304.0, 247.0, 218.0, 237.0, 127.0, 157.99], 'Adam Prentice': [0, 0, 4.0, 3.0, 1.0, 12.08], 'Adrian Killins': [0, 1.0, 0, 0, 0, 6.25], 'Adrian Peterson': [135.0, 114.0, 25.0, 0, 0, -214.97], 'Alec Ingold': [15.0, 26.0, 22.0, 34.0, 22.0, 9.27], 'Alex Armah': [8.0, 6.0, 8.0, 0, 4.0, 8.68], 'Alex Collins': [0, 19.0, 62.0, 0, 0, 92.03], 'Alexander Horvath': [0, 0, 0, 17.0, 0, 10.3], 'Alexander Mattison': [61.0, 79.0, 118.0, 77.0, 124.0, 136.07], 'Alfred Morris': [0.0, 33.0, 0, 0, 0, 56.95], 'Alvin Kamara': [237.0, 364.0, 224.0, 202.0, 223.0, 168.33], 'Ameer Abdullah': [35.0, 27.0, 80.0, 47.0, 32.0, 26.73], 'Andrew Beck': [21.0, 0, 0, 11.0, 30.0, 9.29], 'Andy Janovich': [13.0, 3.0, 11.0, 0, 0, 8.79], 'Anthony McFarland': [0, 14.0, 2.0, 6.0, 3.0, 9.59], 'Anthony Sherman': [3.0, 7.0, 0, 0, 0, 10.3], 'Antonio Gibson': [0, 194.0, 220.0, 152.0, 114.0, 68.1], 'Antonio Williams': [0, 21.0, 0, 0, 0, 21.46], 'Artavis Pierce': [0, 8.0, 0, 0, 0, 15.58], 'Austin Ekeler': [295.0, 156.0, 331.0, 358.0, 174.0, 143.57], 'Austin Walter': [0, 3.0, 16.0, 0, 0, 29.16], 'Avery Williams': [0, 0, 0, 28.0, 0, 30.79], 'Benjamin Snell': [54.0, 70.0, 9.0, 17.0, 0, 33.61], 'Bijan Robinson': [0, 0, 0, 0, 237.0, 206.62], 'Bilal Powell': [26.0, 0, 0, 0, 0, 55.12], 'Bo Scarbrough': [41.0, 3.0, 0, 0, 0, 14.97], 'Boston Scott': [91.0, 83.0, 94.0, 39.0, 11.0, 13.38], 'Brandon Bolden': [47.0, 0, 114.0, 23.0, 10.0, 14.97], 'Breece Hall': [0, 0, 0, 111.0, 274.0, 210.27], 'Brian Hill': [62.0, 83.0, 0, 0, 0, 102.99], 'Brian Robinson': [0, 0, 0, 106.0, 189.0, 157.34], 'Bruce Miller': [0, 1.0, 0, 0, 0, 8.68], 'C.J. Anderson': [3.0, 0, 0, 0, 0, 17.4], 'C.J. Ham': [34.0, 23.0, 27.0, 27.0, 7.0, 11.97], 'C.J. Prosise': [24.0, 12.0, 0, 0, 0, 12.53], 'Caleb Huntley': [0, 0, 0, 40.0, 0, 82.91], 'Cam Akers': [0, 96.0, 4.0, 136.0, 41.0, 42.55], 'Carlos Hyde': [146.0, 76.0, 42.0, 0, 0, 59.99], 'Cartavious Bigsby': [0, 0, 0, 0, 20.0, 35.45], 'Chandler Cox': [0, 2.0, 0, 0, 0, 8.68], 'Chase Brown': [0, 0, 0, 0, 48.0, 44.98], 'Chase Edmonds': [75.0, 152.0, 133.0, 65.0, 33.0, 67.36], 'Chris Carson': [225.0, 178.0, 48.0, 0, 0, -229.61], 'Chris Evans': [0, 0, 44.0, 11.0, 2.0, 14.92], 'Chris Myarick': [0, 0, 10.0, 18.0, 0, 8.68], 'Chris Thompson': [84.0, 38.0, 0, 0, 0, 12.74], 'Christian McCaffrey': [456.0, 86.0, 121.0, 341.0, 378.0, 200.64], 'Christopher Brooks': [0, 0, 0, 0, 9.0, 30.18], 'Christopher Rodriguez': [0, 0, 0, 0, 34.0, 58.77], 'Chuba Hubbard': [0, 0, 127.0, 82.0, 165.0, 191.6], 'Clyde Edwards-Helaire': [0, 165.0, 111.0, 93.0, 58.0, 47.76], 'Cordarrelle Patterson': [24.0, 51.0, 222.0, 141.0, 30.0, -24.45], 'Corey Clement': [-2.0, 15.0, 26.0, 20.0, 0, 20.4], 'Craig Reynolds': [0, 1.0, 31.0, 26.0, 27.0, 42.95], 'Cullen Gillaspia': [0, 1.0, 0, 0, 0, 8.68], "D'Andre Swift": [0, 181.0, 199.0, 180.0, 189.0, 221.42], "D'Ernest Johnson": [13.0, 17.0, 94.0, 4.0, 26.0, 43.22], "D'Onta Foreman": [0, 14.0, 86.0, 122.0, 87.0, 93.5], 'D.J. Foster': [0, 1.0, 0, 0, 0, 9.09], 'Dalvin Cook': [282.0, 330.0, 198.0, 227.0, 33.0, 52.11], 'Dalyn Dawkins': [2.0, 0, 0, 0, 0, 13.95], 'Damarea Crockett': [0, 0, 0.0, 0, 0, 10.1], 'Dameon Pierce': [0, 0, 0, 155.0, 67.0, 93.05], 'Damien Harris': [1.0, 87.0, 204.0, 82.0, 16.0, 13.29], 'Damien Williams': [132.0, 0, 56.0, 0.0, 5.0, 17.4], 'Dan Vitale': [14.0, 0, 0, 0, 0, 9.29], 'Dare Ogunbowale': [70.0, 26.0, 43.0, 42.0, 7.0, 14.77], 'Darrel Williams': [63.0, 45.0, 185.0, 16.0, 0, 61.56], 'Darrell Henderson': [17.0, 119.0, 152.0, 66.0, 40.0, 38.54], 'Darren Sproles': [13.0, 0, 0, 0, 0, 22.07], 'Darrynton Evans': [0, 14.0, 3.0, 9.0, 25.0, 32.91], 'Darwin Thompson': [27.0, 32.0, 0, 0, 0, 28.35], 'David Johnson': [132.0, 170.0, 70.0, 8.0, 0, 60.97], 'David Montgomery': [160.0, 252.0, 185.0, 168.0, 199.0, 196.12], "De'Lance Turner": [0.0, 0, 0, 0, 0, 9.9], "De'Von Achane": [0, 0, 0, 0, 184.0, 170.93], 'DeAndre Washington': [107.0, 14.0, 0, 0, 0, 27.14], 'DeeJay Dallas': [0, 50.0, 53.0, 40.0, 7.0, 30.47], 'Demetric Felton': [0, 0, 46.0, 2.0, 0, 7.87], 'Deon Jackson': [0, 0, 8.0, 79.0, 5.0, 12.14], 'Derek Watt': [11.0, 0, 3.0, 17.0, 0, 12.94], 'Derrick Gore': [0, 0, 50.0, 0, 2.0, 13.95], 'Derrick Henry': [284.0, 323.0, 189.0, 293.0, 238.0, 292.78], 'Derrius Guice': [53.0, 0, 0, 0, 0, 58.37], 'Deuce Vaughn': [0, 0, 0, 0, 11.0, 16.79], 'Devin Singletary': [137.0, 133.0, 182.0, 165.0, 158.0, 190.8], 'Devine Ozigbo': [7.0, 12.0, 1.0, 1.0, 1.0, 9.54], 'Devonta Freeman': [187.0, 34.0, 134.0, 0, 0, 121.57], 'Devontae Booker': [10.0, 75.0, 128.0, 0, 0, 125.9], 'Dexter Williams': [0.0, 0.0, 0, 0, 0, 10.3], 'Dion Lewis': [56.0, 51.0, 0, 0, 0, 32.0], 'Dontrell Hilliard': [33.0, 4.0, 70.0, 71.0, 0, 38.07], 'Duke Johnson': [143.0, 79.0, 54.0, 0.0, 0, 45.52], 'Dwayne Washington': [6.0, 0.0, 2.0, 3.0, 0, 15.52], 'Elijah Dotson': [0, 0, 0, 0, 3.0, 9.9], 'Elijah Mitchell': [0, 0, 157.0, 40.0, 45.0, 107.73], 'Elijhaa Penny': [4.0, 3.0, 31.0, 0, 0, 18.94], 'Emanuel Wilson': [0, 0, 0, 0, 10.0, 25.92], 'Emari Demercado': [0, 0, 0, 0, 66.0, 66.28], 'Eno Benjamin': [0, 0, 24.0, 80.0, 0, 72.16], 'Eric Gray': [0, 0, 0, 0, 9.0, 18.41], 'Evan Hull': [0, 0, 0, 0, 1.0, 8.88], 'Ezekiel Elliott': [300.0, 216.0, 241.0, 176.0, 161.0, 89.63], 'Frank Gore': [84.0, 92.0, 0, 0, 0, 141.11], 'Gabe Nabers': [0, 17.0, 4.0, 0, 0, 10.3], 'Gary Brightwell': [0, 0, 1.0, 25.0, 9.0, 12.59], 'Giovani Bernard': [59.0, 146.0, 54.0, 4.0, 0, 41.11], 'Godwin Igwebuike': [0, 0, 26.0, 1.0, 0, 9.49], 'Greg Howell': [0.0, 7.0, 1.0, 0, 0, 10.92], 'Gus Edwards': [83.0, 120.0, 0, 56.0, 179.0, 172.96], 'Hassan Haskins': [0, 0, 0, 21.0, 0, 27.54], 'Hunter Luepke': [0, 0, 0, 0, 10.0, 12.53], 'Isaiah Spiller': [0, 0, 0, 7.0, 15.0, 28.15], 'Isiah Pacheco': [0, 0, 0, 125.0, 206.0, 198.31], 'Israel Abanikanda': [0, 0, 0, 0, 14.0, 22.88], 'Ito Smith': [32.0, 48.0, 6.0, 0, 0, 28.23], 'J.D. McKissic': [74.0, 180.0, 120.0, 50.0, 0, 48.45], 'J.J. Taylor': [0, 10.0, 18.0, 1.0, 0, 11.43], 'J.K. Dobbins': [0, 159.0, 0, 77.0, 11.0, 13.14], 'JaMycal Hasty': [0, 26.0, 44.0, 63.0, 0, 28.12], 'JaQuan Hardy': [0, 0, 8.0, 0, 0, 14.56], 'Jacques Patrick': [0, 0, 1.0, 0, 0, 11.11], 'Jahmyr Gibbs': [0, 0, 0, 0, 232.0, 200.33], 'Jake Funk': [0, 0, 0.0, 0, 3.0, 10.71], 'Jakob Johnson': [1.0, 16.0, 7.0, 5.0, 2.0, 8.68], 'Jaleel McLaughlin': [0, 0, 0, 0, 95.0, 91.83], 'Jalen Richard': [70.0, 42.0, 17.0, 0, 0, 7.21], 'Jamaal Williams': [135.0, 118.0, 110.0, 217.0, 49.0, 126.35], 'James Conner': [140.0, 153.0, 247.0, 187.0, 191.0, 261.12], 'James Cook': [0, 0, 0, 95.0, 219.0, 236.23], 'James Develin': [0.0, 0, 0, 0, 0, 9.29], 'James Robinson': [0, 237.0, 162.0, 82.0, 1.0, -175.21], 'James White': [187.0, 108.0, 29.0, 0, 0, -4.84], 'Jaret Patterson': [0, 0, 49.0, 7.0, 0, 24.5], 'Jashaun Corbin': [0, 0, 0, 0, 4.0, 8.88], 'Jason Cabinda': [0, 2.0, 12.0, 1.0, 0.0, 10.11], 'Jason Huntley': [0, 2.0, 5.0, 0, 0, 19.02], 'Javonte Williams': [0, 0, 194.0, 40.0, 169.0, 162.25], 'Javorius Allen': [9.0, 0, 0, 0, 0, 15.98], 'Jay Ajayi': [1.0, 0, 0, 0, 0, 14.76], 'Jaylen Samuels': [94.0, 13.0, 4.0, 0, 0, 13.12], 'Jaylen Warren': [0, 0, 0, 80.0, 182.0, 167.68], 'Jeffery Wilson': [43.0, 138.0, 47.0, 150.0, 36.0, 48.59], 'Jeremy McNichols': [0, 36.0, 65.0, 0, 0, 40.32], 'Jerick McKinnon': [0, 118.0, 31.0, 187.0, 77.0, 20.94], 'Jermar Jefferson': [0, 0, 23.0, 0, 0, 23.69], 'Jerome Ford': [0, 0, 0, 0.0, 198.0, 173.56], 'Joe Mixon': [214.0, 95.0, 277.0, 229.0, 249.0, 212.13], 'John Kelly': [0.0, 0, 1.0, 0, 0, 11.32], 'Johnny Stanton': [0, 0, 8.0, 0, 0, 9.69], 'Jon Hilliman': [9.0, 0, 0, 0, 0, 27.14], 'Jonathan Taylor': [0, 242.0, 362.0, 142.0, 146.0, 219.31], 'Jonathan Ward': [0, 8.0, 6.0, 4.0, 1.0, 12.34], 'Jonathan Williams': [38.0, 5.0, 16.0, 22.0, 0.0, 17.54], 'Jordan Howard': [104.0, 27.0, 58.0, 0.0, 0, 90.59], 'Jordan Mason': [0, 0, 0, 28.0, 41.0, 50.46], 'Jordan Scarlett': [0.0, 0, 0, 0, 0, 10.51], 'Jordan Wilkins': [46.0, 53.0, 0, 12.0, 0, 20.44], 'Josh Adams': [0.0, 33.0, 0, 0, 0, 40.52], 'Josh Ferguson': [0.0, 0, 0, 0, 0, 10.51], 'Josh Jacobs': [184.0, 217.0, 213.0, 312.0, 171.0, 213.62], 'Joshua Kelley': [0, 74.0, 12.0, 55.0, 53.0, 66.64], 'Julius Chestnut': [0, 0, 0, 7.0, 0, 11.11], 'Justice Hill': [39.0, 10.0, 0, 35.0, 102.0, 87.17], 'Justin Jackson': [25.0, 60.0, 79.0, 43.0, 0, 61.55], 'Kalen Ballage': [43.0, 85.0, 5.0, 0, 0, 33.65], 'Kareem Hunt': [94.0, 206.0, 104.0, 112.0, 110.0, 100.18], "Ke'Shawn Vaughn": [0, 22.0, 33.0, 7.0, 3.0, 26.34], 'Keaontay Ingram': [0, 0, 0, 14.0, 10.0, 23.69], 'Keaton Mitchell': [0, 0, 0, 0, 64.0, 88.99], 'Keith Smith': [2.0, 15.0, 13.0, 1.0, 5.0, 10.64], 'Kendre Miller': [0, 0, 0, 0, 39.0, 40.32], 'Kene Nwangwu': [0, 0, 7.0, 4.0, 0.0, 11.35], 'Kenjon Barner': [7.0, 0, 0.0, 0, 0, 8.68], 'Kenneth Walker': [0, 0, 0, 191.0, 187.0, 192.22], 'Kenny Gainwell': [0, 0, 113.0, 75.0, 88.0, 82.48], 'Kenyan Drake': [203.0, 180.0, 93.0, 94.0, 4.0, 8.69], 'Kerrith Whyte': [12.0, 0, 0, 0, 0, 33.42], 'Kerryon Johnson': [80.0, 63.0, 0, 0, 0, 45.39], 'Kevin Harris': [0, 0, 0, 9.0, 19.0, 21.86], 'Khalil Herbert': [0, 0, 72.0, 111.0, 102.0, 132.64], 'Khari Blasingame': [8.0, 6.0, 1.0, 0, 5.0, 13.95], 'Kyle Juszczyk': [47.0, 71.0, 65.0, 47.0, 34.0, 10.67], 'Kylin Hill': [0, 0, 2.0, 0.0, 0, 10.1], 'Kyren Williams': [0, 0, 0, 23.0, 248.0, 240.69], 'Lamar Miller': [0, 2.0, 0, 0, 0, 8.68], 'Lamical Perine': [0, 45.0, 2.0, 0, 13.0, 24.3], 'Larry Rountree': [0, 0, 14.0, 4.0, 0, 12.53], 'Latavius Murray': [144.0, 122.0, 96.0, 144.0, 71.0, 84.56], "Le'Veon Bell": [204.0, 68.0, 35.0, 0, 0, 31.97], 'LeSean McCoy': [112.0, 25.0, 0, 0, 0, 14.97], 'LeVante Bellamy': [0, 2.0, 0, 0, 0, 10.91], 'Leonard Fournette': [249.0, 122.0, 242.0, 212.0, 4.0, 71.97], 'Malcolm Brown': [55.0, 99.0, 20.0, 19.0, 0, 49.16], 'Malcolm Perry': [0, 22.0, 0, 0, 0, 9.69], 'Malik Davis': [0, 0, 0, 29.0, 0, 41.33], 'Mark Ingram': [232.0, 47.0, 100.0, 46.0, 0, 113.17], 'Mark Walton': [39.0, 0, 0, 0, 0, 49.44], 'Marlon Mack': [170.0, 8.0, 10.0, 34.0, 0, 72.7], 'Marshawn Lynch': [9.0, 0, 0, 0, 0, 15.58], 'Matt Breida': [94.0, 35.0, 39.0, 47.0, 39.0, 23.71], 'Mekhi Sargent': [0, 0, 0.0, 0, 0, 10.91], 'Melvin Gordon': [173.0, 191.0, 187.0, 78.0, 19.0, 38.76], 'Michael Burton': [0, 6.0, 12.0, 2.0, 5.0, 11.59], 'Michael Carter': [0, 0, 140.0, 114.0, 49.0, -35.13], 'Mike Boone': [46.0, 11.0, 6.0, 23.0, 10.0, 17.45], 'Mike Davis': [9.0, 197.0, 130.0, 3.0, 0, 66.81], 'Miles Sanders': [207.0, 163.0, 110.0, 209.0, 80.0, 127.1], 'Myles Gaskin': [27.0, 158.0, 160.0, 7.0, 0, -53.15], 'Najee Harris': [0, 0, 285.0, 213.0, 185.0, 227.82], 'Nate Cottrell': [0, 0, 0.0, 0, 0, 9.29], 'Nate McCrary': [0, 0, 0.0, 0, 0, 8.48], 'Nick Bawden': [5.0, 0, 3.0, 0, 9.0, 9.49], 'Nick Chubb': [245.0, 200.0, 204.0, 269.0, 22.0, 172.49], 'Nyheim Hines': [96.0, 181.0, 101.0, 63.0, 0, -0.37], 'Patrick DiMarco': [7.0, 0, 0, 0, 0, 10.1], 'Patrick Laird': [61.0, 16.0, 4.0, 0, 0, -23.74], 'Patrick Ricard': [16.0, 16.0, 18.0, 16.0, 15.0, 9.42], 'Patrick Taylor': [0, 0, 15.0, 4.0, 26.0, 37.18], 'Paul Perkins': [2.0, 0, 0, 0, 0, 14.56], 'Peyton Barber': [107.0, 47.0, 46.0, 0, 0, 56.56], 'Phillip Lindsay': [185.0, 60.0, 38.0, 13.0, 0, -87.29], 'Pierre Strong': [0, 0, 0, 26.0, 38.0, 67.7], 'Qadree Ollison': [28.0, 0.0, 16.0, 0, 0, 28.56], 'Rachaad White': [0, 0, 0, 128.0, 256.0, 209.46], 'Raheem Blackshear': [0, 0, 0, 42.0, 11.0, 18.01], 'Raheem Mostert': [157.0, 95.0, 2.0, 158.0, 256.0, 143.46], 'Rashaad Penny': [71.0, 1.0, 114.0, 49.0, 2.0, 68.19], 'Reggie Bonnafon': [24.0, 15.0, 3.0, 0.0, 0, 14.07], 'Reggie Gilliam': [0, 9.0, 3.0, 19.0, 1.0, 8.84], 'Rex Burkhead': [91.0, 99.0, 96.0, 68.0, 0, 83.67], 'Rhamondre Stevenson': [0, 0, 106.0, 236.0, 137.0, 134.22], 'Ricky Ortiz': [1.0, 0, 0, 0, 0, 8.68], 'Rico Dowdle': [0, 2.0, 0, 0, 78.0, 81.89], 'Rodney Smith': [0, 32.0, 9.0, 0, 0, 8.68], 'Ronald Jones II': [156.0, 176.0, 71.0, 14.0, 0, 31.16], 'Ronnie Rivers': [0, 0, 0, 9.0, 17.0, 34.84], 'Roosevelt Nix': [2.0, 0, 0, 0, 0, 8.68], 'Roschon Johnson': [0, 0, 0, 0, 92.0, 80.07], 'Royce Freeman': [130.0, 31.0, 28.0, 17.0, 42.0, 65.9], 'Ryan Nall': [0.0, 19.0, 1.0, 0, 0, 9.29], 'Ryquell Armstead': [45.0, 0, 11.0, 0, 0, 24.9], 'Salvon Ahmed': [0, 64.0, 29.0, 12.0, 38.0, 25.7], 'Samaje Perine': [1.0, 59.0, 73.0, 129.0, 110.0, 56.95], 'Saquon Barkley': [233.0, 14.0, 142.0, 271.0, 214.0, 163.07], 'Scottie Phillips': [0, 1.0, 3.0, 0, 0, 11.32], 'Sean Tucker': [0, 0, 0, 0, 3.0, 13.34], 'Senorise Perry': [1.0, 0.0, 0, 0, 0, 10.51], 'Snoop Conner': [0, 0, 0, 8.0, 0, 17.2], 'Sony Michel': [145.0, 69.0, 137.0, 19.0, 0, 135.36], 'Spencer Brown': [0, 0, 0, 6.0, 0, 17.4], 'Spencer Ware': [11.0, 0, 0, 0, 0, 19.02], 'T.J. Logan': [3.0, 0, 0, 0, 0, 10.71], 'T.J. Yeldon': [27.0, 15.0, 0, 0, 0, 22.88], 'Taiwan Jones': [5.0, 0, 0, -1.0, 0, 8.68], 'Tarik Cohen': [146.0, 16.0, 0, 0, 0, 23.69], 'Tevin Coleman': [126.0, 11.0, 43.0, 21.0, 0, 81.14], 'Theo Riddick': [0, 10.0, 0, 0, 0, 11.52], 'Todd Gurley': [211.0, 151.0, 0, 0, 0, 146.18], 'Tony Brooks-James': [1.0, 0.0, 0, 0, 0, 9.49], 'Tony Jones': [0, 1.0, 18.0, 8.0, 30.0, 26.9], 'Tony Pollard': [82.0, 109.0, 145.0, 237.0, 210.0, 199.47], 'Tra Carson': [9.0, 0, 0, 0, 0, 18.41], 'Travis Etienne': [0, 0, 0, 194.0, 266.0, 213.11], 'Travis Homer': [25.0, 28.0, 48.0, 37.0, 0, 34.97], 'Trayveon Williams': [0, 19.0, 5.0, 5.0, 11.0, 27.07], 'Trenton Cannon': [0, 6.0, -1.0, 0, 0, 9.49], 'Trestan Ebner': [0, 0, 0, 5.0, 0, 19.63], 'Trey Edmunds': [17.0, 0, 0, 0, 0, 27.34], 'Trey Ragas': [0, 0, 2.0, 0, 0, 10.51], 'Trey Sermon': [0, 0, 25.0, 1.0, 16.0, 41.07], 'Troy Hairston': [0, 0, 0, 5.0, 0, 8.68], 'Troymaine Pope': [10.0, 17.0, 0, 0, 0, 24.09], 'Ty Chandler': [0, 0, 0, 2.0, 91.0, 102.17], 'Ty Johnson': [50.0, 57.0, 109.0, 36.0, 27.0, 23.6], "Ty'Son Williams": [0, 0, 37.0, 1.0, 0, 8.68], 'Tyjae Spears': [0, 0, 0, 0, 137.0, 100.55], 'Tyler Allgeier': [0, 0, 0, 152.0, 127.0, 147.2], 'Tyler Badie': [0, 0, 0, 9.0, 0, 8.68], 'Tyler Ervin': [3.0, 20.0, 0, 0, 0, 22.27], 'Tyler Goodson': [0, 0, 0, 0, 16.0, 26.32], 'Tyrion Davis-Price': [0, 0, 0, 8.0, 2.0, 12.94], 'Wayne Gallman': [46.0, 125.0, 11.0, 0, 0, 29.79], 'Wendell Smallwood': [17.0, 0, 8.0, 0, 0, 13.75], 'Wes Hills': [16.0, 0, 0, 0, 0, 12.94], 'Zach Charbonnet': [0, 0, 0, 0, 94.0, 102.38], 'Zach Evans': [0, 0, 0, 0, 1.0, 12.53], 'Zach Line': [8.0, 0, 0, 0, 0, 12.74], 'Zach Zenner': [3.0, 0, 0, 0, 0, 8.27], 'Zack Moss': [0, 93.0, 95.0, 57.0, 159.0, 223.48], 'Zamir White': [0, 0, 0, 4.0, 67.0, 100.15], 'Zonovan Knight': [0, 0, 0, 54.0, 2.0, 11.32]}

In [49]:
import json
json_data = json.dumps(name_fantasy_dict, indent=4)
with open('../Flask/static/RBYearlyPoints.json','w') as json_file:
    json_file.write(json_data)

In [ ]:
####Final Model We Used ####

In [ ]:
X = RB.drop(['Fantasy Points'], axis=1)
y = RB['Fantasy Points']


numeric_features = ['Rush Yards']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
      
    ]
)


pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

X_train_subset = X_train[X_train.index.year < 2023]
y_train_subset = y_train[y_train.index.year < 2023]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2023]
y_test_subset = y_test[y_test.index.year == 2023]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")