In [1]:
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
from matplotlib import pyplot
from datetime import datetime
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [2]:
DataFrame = pd.read_csv('../Data.csv')

In [3]:
WR = DataFrame[DataFrame['Position'] == 'WR']

In [4]:
WR = WR.drop(columns = ['Week','Position','Game','Unnamed: 0'])

In [5]:
WR = WR.drop(columns = ['PassingYards','PassingTDs','Ints','Rush Attempts', 'Rush Yards','Fumbles','RushTDs'])

In [6]:
WR['Style'] = ''
WR['Skill'] = ''

In [7]:
WR = WR.groupby(['Name','Year']).sum()

In [8]:
WR.reset_index(inplace=True)
WR.set_index('Year', inplace = True)

In [9]:
WR.index = pd.to_datetime(WR.index, format='%Y')

In [10]:
WR = WR.rename(columns = {'Fantasy Points':'Fantasy_Points'})
index_dtype = WR.index.dtype
print("Index Data Type:", index_dtype)

Index Data Type: datetime64[ns]

In [ ]:
WR

In [11]:
WR.loc[(WR['Receiving TDs'] >= 10) , 'Style'] = 'Touchdown Machine'
WR.loc[(WR['Receiving TDs'] < 10) & (WR['Receptions'] >= 85), 'Style'] = 'Catch Monster'
WR.loc[(WR['Receiving TDs'] < 10) & (WR['Receptions'] < 85), 'Style'] = 'Regular'

In [12]:
WR.loc[(WR['Receiving Yards'] >= 1200) , 'Skill'] = 'Elite'
WR.loc[(WR['Receiving Yards'] >= 700) & (WR['Receiving Yards'] < 1200), 'Skill'] = 'Starter'
WR.loc[(WR['Receiving Yards'] < 700), 'Skill'] = 'Back Up'

In [77]:
#testing with 2022 data and Receiving Yards being the feature 
X = WR.drop(['Fantasy_Points'], axis=1)
y = WR['Fantasy_Points']



numeric_features = ['Receiving Yards']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
 
    ]
)




pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


X_train_subset = X_train[X_train.index.year < 2022]
y_train_subset = y_train[y_train.index.year < 2022]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2022]
y_test_subset = y_test[y_test.index.year == 2022]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 109.7148946034343
R-squared: 0.9877669301141293

In [75]:
#same test but with receiving TDs
X = WR.drop(['Fantasy_Points'], axis=1)
y = WR['Fantasy_Points']



numeric_features = ['Receiving TDs']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
      
    ]
)




pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


X_train_subset = X_train[X_train.index.year < 2022]
y_train_subset = y_train[y_train.index.year < 2022]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2022]
y_test_subset = y_test[y_test.index.year == 2022]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 1203.4137407350775
R-squared: 0.8658209129650073

In [76]:
#test with 2023
X = WR.drop(['Fantasy_Points'], axis=1)
y = WR['Fantasy_Points']


numeric_features = ['Receiving Yards']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),

    ]
)




pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])


X_train_subset = X_train[X_train.index.year < 2023]
y_train_subset = y_train[y_train.index.year < 2023]
pipeline.fit(X_train_subset, y_train_subset)


X_test_subset = X_test[X_test.index.year == 2023]
y_test_subset = y_test[y_test.index.year == 2023]
y_pred = pipeline.predict(X_test_subset)


mse = mean_squared_error(y_test_subset, y_pred)
r2 = r2_score(y_test_subset, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

Mean Squared Error: 253.38984955597175
R-squared: 0.9757928345150757

In [15]:
#Arima Model to conduct a trend analysis that predicts 2024 Receving Yards to then put in model to make final FF point prediction

In [16]:
features = ['Receiving TDs', 'Receptions']
target_variable = 'Receiving Yards'

In [36]:
players = WR['Name'].unique()

# Create a dictionary to store predictions for each player
predictions_2024 = {}

for player in players:
    player_data = WR[WR['Name'] == player]
    time_series = player_data[features + [target_variable]]
    
    try:
        # Fit an ARIMA model
        model = ARIMA(time_series[target_variable], order=(1, 1, 1))  # Adjust the order as needed
        arima_result = model.fit()
        
        # Predict Fantasy Points for 2024
        start_date_2024 = datetime(2024, 1, 1)
        end_date_2024 = datetime(2024, 12, 31)
        y_pred_2024 = arima_result.predict(start=start_date_2024, end=end_date_2024, dynamic=False)
        
        # Store predictions in the dictionary
        predictions_2024[player] = y_pred_2024.values[-1]  # Only store the prediction for 2024
        
        
        
    except Exception as e:
        continue

In [37]:
predictions_2024

{'A.J. Brown': 1424.515994190584,
 'A.J. Green': 689.5532052288504,
 'Adam Humphries': 382.68673572578854,
 'Adam Thielen': 891.3236359646016,
 'Allen Lazard': 487.3780474943746,
 'Allen Robinson': 403.49803486350504,
 'Amari Cooper': 1121.9764981992953,
 'Amon-Ra St. Brown': 2230.1038060551564,
 'Andre Roberts': 34.296936562887566,
 'Andy Isabella': 82.25362161462314,
 'Anthony Miller': -461.8132952709001,
 'Antonio Brown': 495.8664154032123,
 'Ashton Dulin': 190.05818979384807,
 'Auden Tate': 75.2732143757205,
 'Bennett Skowronek': 83.87735051587651,
 'Brandin Cooks': 659.176588295759,
 'Brandon Aiyuk': 1975.0126522367666,
 'Brandon Zylstra': 246.32023244638435,
 'Braxton Berrios': 261.7672797089231,
 'Breshad Perriman': 168.312546914085,
 'Bryan Edwards': 544.0632381380533,
 'Byron Pringle': 239.57136261589764,
 'C.J. Board': 44.198407001989814,
 'Cam Sims': 221.43864338316513,
 'Cedrick Wilson': 256.26948205226597,
 'CeeDee Lamb': 2564.4861873493674,
 'Chase Claypool': -63.75287692061141,
 'Chris Conley': -84.59087701192625,
 'Chris Godwin': 1027.8178578458526,
 'Chris Hogan': 62.16359263076601,
 'Christian Blake': 89.86189631546725,
 'Christian Kirk': 807.7994714703979,
 'Cody Hollister': 61.852069762088824,
 'Cole Beasley': -921.050256116279,
 'Cooper Kupp': 1090.925637962296,
 'Corey Davis': 650.0441506903352,
 'Courtland Sutton': 694.1881014063741,
 'Curtis Samuel': 548.661712785358,
 "D'Wayne Eskridge": -5.379104300227463,
 'D.J. Chark': 589.1906064496852,
 'D.J. Moore': 1199.9887148347623,
 'D.K. Metcalf': 1092.9194366833665,
 'Damiere Byrd': 383.6751693677125,
 'Danny Amendola': 88.64741351915038,
 'Dante Pettis': 291.7367004151857,
 'Darius Slayton': 658.7635610010918,
 'Darnell Mooney': 618.2347088731996,
 'Davante Adams': 372.9098707813494,
 'DeAndre Carter': 206.30499788533209,
 'DeAndre Hopkins': 970.8156700375293,
 'DeSean Jackson': 258.7881815918865,
 'DeVante Parker': 252.40249140093758,
 'DeVonta Smith': 1066.1485653955235,
 'Dede Westbrook': 241.35349307233878,
 'Deebo Samuel': 891.960251789664,
 'Demarcus Robinson': 396.1495273722926,
 'Denzel Mims': 224.3333341907154,
 'Deonte Harty': 190.7151370416835,
 'Devin Duvernay': 190.91238879871227,
 'Diontae Johnson': 745.6242977630428,
 'Diontae Spencer': -11.111672495958175,
 'Donovan Peoples-Jones': 473.50984305963004,
 'Dyami Brown': 167.90906877725692,
 'Elijah Moore': 639.898773865402,
 'Emmanuel Sanders': 397.6545691220215,
 'Equanimeous St. Brown': 138.16104817516415,
 'Freddie Swain': 324.8985730020494,
 'Gabriel Davis': 746.0310986951832,
 'Greg Ward': 253.99878704051713,
 'Gunner Olszewski': 0.0034226476299892283,
 'Hunter Renfrow': 518.6839771191284,
 'Ihmir Smith-Marsette': 50.0170209540785,
 'Isaiah Ford': 227.355484637288,
 'Isaiah McKenzie': 121.05186860677003,
 'J.J. Arcega-Whiteside': -26.45590922609744,
 "Ja'Marr Chase": 1206.0583970016912,
 'Jake Kumerow': 97.42782843764903,
 'Jakeem Grant': 141.5428827933723,
 'Jakobi Meyers': 885.3382545364484,
 'Jalen Guyton': 89.00000261560042,
 'Jalen Reagor': 162.08504824673852,
 'Jamal Agnew': 230.33384771822293,
 'James Proche': 71.70794348459151,
 'James Washington': 320.1847785825562,
 'Jamison Crowder': 236.48004124903096,
 'Jarvis Landry': -690.4667860275886,
 'Jauan Jennings': 267.1877137473764,
 'Jaylen Waddle': 1014.0027548349566,
 'Jeff Smith': 120.50626307109206,
 'Jerry Jeudy': 758.1369690853301,
 'John Ross': 215.07433807825794,
 'Josh Palmer': 581.1773787552576,
 'Josh Reynolds': 547.495565773157,
 'JuJu Smith-Schuster': 364.0693216103433,
 'Julio Jones': -363.4883182746869,
 'Justin Jefferson': 1423.403860025671,
 'K.J. Osborn': 535.4666635733333,
 'KJ Hamler': 197.94838498120325,
 'Kadarius Toney': 207.26852041887952,
 'Kalif Raymond': 498.75007531232797,
 'Keelan Cole': 113.57050316956344,
 'Keenan Allen': 1181.883972230843,
 'Keith Kirkwood': 45.26632889976493,
 'Keke Coutee': 151.0061080941106,
 'Kendall Hinton': 622.9484037937732,
 'Kendrick Bourne': 441.5461601908411,
 'Kenny Golladay': 526.1139947732966,
 'Kenny Stills': 84.26355383413824,
 'Khadarel Hodge': 275.1536609789509,
 'Laquon Treadwell': 140.29027218945382,
 'Laviska Shenault': 74.11780941581272,
 "Lil'Jordan Humphrey": 161.75341784555442,
 'Mack Hollins': 282.31539378999605,
 'Marcus Johnson': 93.39348803372742,
 'Marquez Callaway': 716.5387827648536,
 'Marquez Valdes-Scantling': 321.6477006067306,
 'Marquise Brown': 661.6042074306547,
 'Marvin Hall': 168.98593481801817,
 'Marvin Jones': -751.6356650881781,
 'Mecole Hardman': 131.31412420122962,
 'Michael Gallup': 353.76103213457316,
 'Michael Pittman': 1151.929195106842,
 'Mike Evans': 1334.6900786368813,
 'Mike Strachan': 45.47459789086285,
 'Mike Thomas': 66.69672859074385,
 'Mike Williams': 700.144371229231,
 'Miles Boykin': 69.37090686196206,
 'Mohamed Sanu': 277.2262298519798,
 "N'Keal Harry": 185.36536496229294,
 'Nelson Agholor': 489.7841936248809,
 'Nick Westbrook': 307.1250988831323,
 'Nico Collins': 1297.0015684050497,
 'Noah Brown': 653.2163496135215,
 'Olamide Zaccheaus': 248.96291891879883,
 'Parris Campbell': 216.41971950858374,
 'Penny Hart': 64.97147528009066,
 'Pharoh Cooper': -37.25298071319147,
 'Preston Williams': -613.4637906215596,
 'Quez Watkins': 317.3964142277958,
 'Quintez Cephus': -548.0046682799227,
 'Randall Cobb': -199.67563453215084,
 'Rashard Higgins': 275.15274256224217,
 'Rashod Bateman': 375.85194174483627,
 'Ray Ray McCloud': 136.38763347584495,
 'Robbie Chosen': 222.5488251407679,
 'Robert Woods': 158.79702010728047,
 'Rondale Moore': 298.9277108737082,
 'Russell Gage': 206.47349049974315,
 'Sammy Watkins': 119.15059634736758,
 'Scott Miller': 215.59734367966547,
 'Stefon Diggs': 1203.333031912899,
 'Sterling Shepard': 0.7511660456384295,
 'T.Y. Hilton': 312.18823889557734,
 'Tavon Austin': 211.93146633586952,
 'Tee Higgins': 297.70467127603627,
 'Terrace Marshall': 139.00239437685684,
 'Terry McLaurin': 1002.0016311127308,
 'Tim Patrick': 849.3241004433424,
 "Tre'Quan Smith": 341.15878715256105,
 'Trent Sherfield': 143.7185751316368,
 'Trent Taylor': 0.0012837021782701186,
 'Trenton Irwin': 297.66507711528646,
 'Ty Montgomery': 37.36718281257338,
 'Tylan Wallace': 19.519908747699986,
 'Tyler Boyd': 517.0942299969877,
 'Tyler Lockett': 968.0634284041412,
 'Tyreek Hill': 2166.902263370551,
 'Tyron Johnson': -20.840512712846138,
 'Van Jefferson': 401.4106041545917,
 'Will Fuller': 512.7287199515606,
 'Zach Pascal': -86.99091153380064,
 'Zay Jones': 368.06002895515417}

In [43]:
Predictions24 = pd.DataFrame(list(predictions_2024.items()), columns=['Name', 'Receiving Yards'])

In [44]:
Predictions24

               Name  Receiving Yards
0        A.J. Brown      1424.515994
1        A.J. Green       689.553205
2    Adam Humphries       382.686736
3      Adam Thielen       891.323636
4      Allen Lazard       487.378047
..              ...              ...
167   Tyron Johnson       -20.840513
168   Van Jefferson       401.410604
169     Will Fuller       512.728720
170     Zach Pascal       -86.990912
171       Zay Jones       368.060029

[172 rows x 2 columns]

In [54]:
Predictions24['Year'] = 2024

In [55]:
Predictions24

               Name  Receiving Yards  Year
0        A.J. Brown      1424.515994  2024
1        A.J. Green       689.553205  2024
2    Adam Humphries       382.686736  2024
3      Adam Thielen       891.323636  2024
4      Allen Lazard       487.378047  2024
..              ...              ...   ...
167   Tyron Johnson       -20.840513  2024
168   Van Jefferson       401.410604  2024
169     Will Fuller       512.728720  2024
170     Zach Pascal       -86.990912  2024
171       Zay Jones       368.060029  2024

[172 rows x 3 columns]

In [58]:
Predictions24.reset_index(inplace=True)
Predictions24.set_index('Year', inplace = True)
Predictions24.index = pd.to_datetime(Predictions24.index, format='%Y')

In [59]:
Predictions24.reset_index(inplace=True)

In [61]:
Predictions24.drop(columns = ['index'])

          Year            Name  Receiving Yards
0   2024-01-01      A.J. Brown      1424.515994
1   2024-01-01      A.J. Green       689.553205
2   2024-01-01  Adam Humphries       382.686736
3   2024-01-01    Adam Thielen       891.323636
4   2024-01-01    Allen Lazard       487.378047
..         ...             ...              ...
167 2024-01-01   Tyron Johnson       -20.840513
168 2024-01-01   Van Jefferson       401.410604
169 2024-01-01     Will Fuller       512.728720
170 2024-01-01     Zach Pascal       -86.990912
171 2024-01-01       Zay Jones       368.060029

[172 rows x 3 columns]

In [62]:
Predictions24

          Year  index            Name  Receiving Yards
0   2024-01-01      0      A.J. Brown      1424.515994
1   2024-01-01      1      A.J. Green       689.553205
2   2024-01-01      2  Adam Humphries       382.686736
3   2024-01-01      3    Adam Thielen       891.323636
4   2024-01-01      4    Allen Lazard       487.378047
..         ...    ...             ...              ...
167 2024-01-01    167   Tyron Johnson       -20.840513
168 2024-01-01    168   Van Jefferson       401.410604
169 2024-01-01    169     Will Fuller       512.728720
170 2024-01-01    170     Zach Pascal       -86.990912
171 2024-01-01    171       Zay Jones       368.060029

[172 rows x 4 columns]

In [38]:
ReceivngYards = WR.drop(columns = ['Receptions','Receiving TDs'])

In [47]:
ReceivngYards = ReceivngYards.reset_index()

In [48]:
ReceivngYards

,Year,Name,Fantasy_Points,Receiving Yards,Style,Skill
0,2019-01-01,A.J. Brown,210.0,1051.0,Regular,Starter
1,2020-01-01,A.J. Brown,237.0,1075.0,Touchdown Machine,Starter
2,2021-01-01,A.J. Brown,174.0,869.0,Regular,Starter
3,2022-01-01,A.J. Brown,293.0,1496.0,Touchdown Machine,Elite
4,2023-01-01,A.J. Brown,283.0,1456.0,Catch Monster,Elite
...,...,...,...,...,...,...
1086,2019-01-01,Zay Jones,43.0,216.0,Regular,Back Up
1087,2020-01-01,Zay Jones,32.0,154.0,Regular,Back Up
1088,2021-01-01,Zay Jones,101.0,546.0,Regular,Back Up
1089,2022-01-01,Zay Jones,190.0,823.0,Regular,Starter
1090,2023-01-01,Zay Jones,74.0,321.0,Regular,Back Up

In [63]:
concatenated_df = pd.concat([ReceivngYards, Predictions24])

In [64]:
concatenated_df

,Year,Name,Fantasy_Points,Receiving Yards,Style,Skill,index
0,2019-01-01,A.J. Brown,210.0,1051.000000,Regular,Starter,NaN
1,2020-01-01,A.J. Brown,237.0,1075.000000,Touchdown Machine,Starter,NaN
2,2021-01-01,A.J. Brown,174.0,869.000000,Regular,Starter,NaN
3,2022-01-01,A.J. Brown,293.0,1496.000000,Touchdown Machine,Elite,NaN
4,2023-01-01,A.J. Brown,283.0,1456.000000,Catch Monster,Elite,NaN
...,...,...,...,...,...,...,...
167,2024-01-01,Tyron Johnson,NaN,-20.840513,NaN,NaN,167.0
168,2024-01-01,Van Jefferson,NaN,401.410604,NaN,NaN,168.0
169,2024-01-01,Will Fuller,NaN,512.728720,NaN,NaN,169.0
170,2024-01-01,Zach Pascal,NaN,-86.990912,NaN,NaN,170.0
171,2024-01-01,Zay Jones,NaN,368.060029,NaN,NaN,171.0

In [65]:
ReceivingYards2 = concatenated_df.sort_values(by=['Name','Year'], ascending=True)

In [71]:
ReceivingYards2 = ReceivingYards2.drop(columns = ['index'])

In [72]:
ReceivingYards2

,Year,Name,Fantasy_Points,Receiving Yards,Style,Skill
0,2019-01-01,A.J. Brown,210.0,1051.000000,Regular,Starter
1,2020-01-01,A.J. Brown,237.0,1075.000000,Touchdown Machine,Starter
2,2021-01-01,A.J. Brown,174.0,869.000000,Regular,Starter
3,2022-01-01,A.J. Brown,293.0,1496.000000,Touchdown Machine,Elite
4,2023-01-01,A.J. Brown,283.0,1456.000000,Catch Monster,Elite
...,...,...,...,...,...,...
1087,2020-01-01,Zay Jones,32.0,154.000000,Regular,Back Up
1088,2021-01-01,Zay Jones,101.0,546.000000,Regular,Back Up
1089,2022-01-01,Zay Jones,190.0,823.000000,Regular,Starter
1090,2023-01-01,Zay Jones,74.0,321.000000,Regular,Back Up
171,2024-01-01,Zay Jones,NaN,368.060029,NaN,NaN

In [78]:
import pandas as pd
from datetime import datetime

# Assuming 'WR_merged' is your DataFrame containing the merged data with predicted yards
# Assuming 'pipeline' is your trained pipeline

# Filter 'WR_merged' to keep only the most recent prediction for each player
latest_predictions = ReceivingYards2.groupby('Name')['Receiving Yards'].last().reset_index()

# Preprocess the data for prediction
X_2024 = latest_predictions[['Receiving Yards']]

# Make predictions for fantasy points in 2024
y_pred_2024 = pipeline.predict(X_2024)

# Combine player names and their corresponding predicted fantasy points
player_predictions = pd.DataFrame({
    'Player': latest_predictions['Name'],
    'Predicted_Fantasy_Points_2024': y_pred_2024.round(2)  # Round predictions to 2 decimal places
})

# Print the predicted fantasy points for 2024
print(player_predictions)

                Player  Predicted_Fantasy_Points_2024
0           A.J. Brown                         299.23
1           A.J. Green                         144.51
2           A.T. Perry                          51.14
3       Adam Humphries                          79.91
4         Adam Thielen                         186.99
..                 ...                            ...
415      Xavier Gipson                          47.56
416  Xavier Hutchinson                          18.30
417        Zach Pascal                         -18.96
418        Zay Flowers                         179.97
419          Zay Jones                          76.83

[420 rows x 2 columns]

In [79]:
player_predictions

                Player  Predicted_Fantasy_Points_2024
0           A.J. Brown                         299.23
1           A.J. Green                         144.51
2           A.T. Perry                          51.14
3       Adam Humphries                          79.91
4         Adam Thielen                         186.99
..                 ...                            ...
415      Xavier Gipson                          47.56
416  Xavier Hutchinson                          18.30
417        Zach Pascal                         -18.96
418        Zay Flowers                         179.97
419          Zay Jones                          76.83

[420 rows x 2 columns]

In [87]:
DataFrame = pd.read_csv('../Data.csv')

In [95]:
WR2 = DataFrame[DataFrame['Position'] == 'WR']

In [96]:
WR2 = WR2.drop(columns = ['PassingYards','PassingTDs','Ints','Rush Attempts', 'Rush Yards','Fumbles','RushTDs'])

In [97]:
WR2 = WR2.drop(columns = ['Week','Position','Game','Unnamed: 0'])

In [99]:
WR2 = WR2.groupby(['Name','Year']).sum()

In [100]:
WR2

                 Fantasy Points  Receptions  Receiving Yards  Receiving TDs
Name       Year
A.J. Brown 2019           210.0        52.0           1051.0            8.0
           2020           237.0        70.0           1075.0           11.0
           2021           174.0        63.0            869.0            5.0
           2022           293.0        88.0           1496.0           11.0
           2023           283.0       106.0           1456.0            7.0
...                         ...         ...              ...            ...
Zay Jones  2019            43.0        27.0            216.0            0.0
           2020            32.0        14.0            154.0            1.0
           2021           101.0        47.0            546.0            1.0
           2022           190.0        82.0            823.0            5.0
           2023            74.0        34.0            321.0            2.0

[1091 rows x 4 columns]

In [101]:
WR2.reset_index(inplace=True)

In [104]:
WR2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1091 entries, 0 to 1090
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             1091 non-null   object
 1   Year             1091 non-null   int64
 2   Fantasy Points   1091 non-null   float64
 3   Receptions       1091 non-null   float64
 4   Receiving Yards  1091 non-null   float64
 5   Receiving TDs    1091 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 51.3+ KB

In [109]:

# Create an empty dictionary to store the player names and their fantasy points by year
name_fantasy_dict = {}

# Iterate over the rows of the DataFrame
for index, row in WR2.iterrows():
    name = row['Name']
    year = row['Year']
    fantasy_points = row['Fantasy Points']
    
    if name not in name_fantasy_dict:  # If the player is not already in the dictionary
        name_fantasy_dict[name] = [fantasy_points if y == year else 0 for y in range(2019, 2024)]
    else:
        # If the player is already in the dictionary, update the corresponding value list
        name_fantasy_dict[name][year - 2019] = fantasy_points

# Print the resulting dictionary
print(name_fantasy_dict)

{'A.J. Brown': [210.0, 237.0, 174.0, 293.0, 283.0], 'A.J. Green': [0, 107.0, 150.0, 58.0, 0], 'A.T. Perry': [0, 0, 0, 0, 57.0], 'Adam Humphries': [83.0, 54.0, 73.0, 0, 0], 'Adam Thielen': [110.0, 246.0, 195.0, 171.0, 223.0], 'Albert Wilson': [81.0, 0, 43.0, 0, 0], 'Alec Pierce': [0, 0, 0, 107.0, 90.0], 'Alex Bachman': [0, 0, 0.0, 0, 0], 'Alex Erickson': [90.0, 19.0, 7.0, 0, 41.0], 'Alexander Hollins': [6.0, 0, 0, 0, 0], 'Allen Hurns': [79.0, 0, 0, 0, 0], 'Allen Lazard': [97.0, 92.0, 136.0, 167.0, 55.0], 'Allen Robinson': [248.0, 258.0, 82.0, 81.0, 56.0], 'Alshon Jeffery': [117.0, 22.0, 0, 0, 0], 'Amari Cooper': [238.0, 232.0, 195.0, 240.0, 219.0], 'Amari Rodgers': [0, 0, 7.0, 37.0, 0], 'Amon-Ra St. Brown': [0, 0, 219.0, 255.0, 324.0], 'Andre Baccellia': [0, 0, 0, 9.0, 0], 'Andre Patton': [9.0, 0, 0, 0, 0], 'Andre Roberts': [3.0, 4.0, 2.0, 0, 0], 'Andrei Iosivas': [0, 0, 0, 0, 46.0], 'Andy Isabella': [31.0, 51.0, 2.0, 4.0, 0], 'Anthony Miller': [123.0, 101.0, 14.0, 0, 0], 'Anthony Schwartz': [0, 0, 30.0, 17.0, 0], 'Antoine Green': [0, 0, 0, 0, 1.0], 'Antoine Wesley': [0, 0, 54.0, 0, 0], 'Antonio Brown': [15.0, 113.0, 118.0, 0, 0], 'Antonio Callaway': [16.0, 3.0, 0, 0, 0], 'Antonio Gandy-Golden': [0, 3.0, 0, 0, 0], 'Ashton Dulin': [3.0, 7.0, 42.0, 37.0, 0], 'Auden Tate': [97.0, 26.0, 11.0, 0, 0], 'Austin Carr': [1.0, 11.0, 0, 0, 0], 'Austin Mack': [0, 14.0, 0, 0, 0], 'Austin Trammell': [0, 0, 0, 2.0, 5.0], 'Bennett Skowronek': [0, 0, 22.0, 79.0, 21.0], 'Bennie Fowler': [44.0, 3.0, 0, 0, 0], 'Bo Melton': [0, 0, 0, 0, 43.0], 'Brandin Cooks': [109.0, 226.0, 223.0, 139.0, 163.0], 'Brandon Aiyuk': [0, 179.0, 162.0, 220.0, 241.0], 'Brandon Johnson': [0, 0, 0, 15.0, 69.0], 'Brandon Powell': [0, 25.0, 0, 41.0, 63.0], 'Brandon Zylstra': [17.0, 5.0, 45.0, 0, 0], 'Braxton Berrios': [14.0, 91.0, 109.0, 52.0, 53.0], 'Braylon Sanders': [0, 0, 0, 2.0, 0], 'Breshad Perriman': [134.0, 94.0, 31.0, 23.0, 0], 'Britain Covey': [0, 0, 0, 0, 7.0], 'Bryan Edwards': [0, 33.0, 104.0, 4.0, 0], 'Byron Pringle': [32.0, 33.0, 121.0, 33.0, 25.0], 'C.J. Board': [4.0, 18.0, 7.0, 1.0, 0], 'C.J. Saunders': [0, 0, 3.0, 0, 0], 'Cade Johnson': [0, 0, 0, 4.0, 0], 'Calvin Austin': [0, 0, 0, 0, 47.0], 'Calvin Ridley': [190.0, 278.0, 70.0, 0, 223.0], 'Cam Sims': [4.0, 82.0, 44.0, 14.0, 0], 'Cameron Batson': [0, 26.0, 10.0, 0, 0], 'Cedric Tillman': [0, 0, 0, 0, 40.0], 'Cedrick Wilson': [9.0, 51.0, 139.0, 23.0, 66.0], 'CeeDee Lamb': [0, 201.0, 225.0, 293.0, 392.0], 'Chad Beebe': [8.0, 48.0, 0, 0, 0], 'Chad Hansen': [0, 44.0, 0, 0, 0], 'Charlie Jones': [0, 0, 0, 0, 13.0], 'Chase Claypool': [0, 207.0, 159.0, 100.0, 19.0], 'Chatarius Atwell': [0, 0, 0, 60.0, 105.0], 'Chester Rogers': [43.0, 0, 60.0, -1.0, 0], 'Chris Conley': [148.0, 91.0, 62.0, 7.0, 9.0], 'Chris Godwin': [272.0, 185.0, 237.0, 219.0, 200.0], 'Chris Hogan': [12.0, 25.0, 13.0, 0, 0], 'Chris Lacy': [8.0, 0, 0, 0, 0], 'Chris Moore': [4.0, 0, 53.0, 111.0, 61.0], 'Chris Olave': [0, 0, 0, 196.0, 223.0], 'Christian Blake': [18.0, 24.0, 5.0, 0, 0], 'Christian Kirk': [157.0, 139.0, 199.0, 235.0, 145.0], 'Christian Watson': [0, 0, 0, 155.0, 98.0], 'Cody Core': [5.0, 0, 0, 0, 0], 'Cody Hollister': [3.0, 2.0, 6.0, 8.0, 0], 'Cody Latimer': [62.0, 0, 0, 0, 0], 'Cody Thompson': [0, 0, 0, 0, 2.0], 'Cody White': [0, 0, 7.0, 1.0, 0], 'Cole Beasley': [178.0, 203.0, 153.0, 7.0, 0], 'Collin Johnson': [0, 55.0, 20.0, 0, 2.0], 'Colton Dowell': [0, 0, 0, 0, 1.0], 'Cooper Kupp': [265.0, 203.0, 430.0, 197.0, 158.0], 'Corey Davis': [108.0, 187.0, 102.0, 91.0, 0], 'Courtland Sutton': [215.0, 9.0, 141.0, 154.0, 187.0], 'Curtis Samuel': [162.0, 199.0, 7.0, 166.0, 149.0], 'Cyril Grayson': [1.0, 0, 44.0, 0, 0], "D'Wayne Eskridge": [0, 0, 26.0, 11.0, 1.0], "D'haquille Williams": [32.0, 0, 0, 0, 0], 'D.J. Chark': [218.0, 148.0, 32.0, 93.0, 108.0], 'D.J. Montgomery': [0, 0, 6.0, 0, 13.0], 'D.J. Moore': [225.0, 205.0, 229.0, 189.0, 280.0], 'D.J. Turner': [0, 0, 0, 2.0, 0], 'D.K. Metcalf': [182.0, 266.0, 237.0, 222.0, 218.0], "Da'Mari Scott": [4.0, 0, 0, 0, 0], 'DaeSean Hamilton': [59.0, 58.0, 0, 0, 0], 'Damiere Byrd': [69.0, 107.0, 62.0, 48.0, 0], 'Damion Ratley': [36.0, 9.0, 0, 0, 0], 'Damion Willis': [15.0, 0, 0, 0, 0], 'Danny Amendola': [135.0, 101.0, 65.0, 0, 0], 'Danny Gray': [0, 0, 0, 2.0, 0], 'Dante Pettis': [32.0, 16.0, 23.0, 59.0, 0], 'Dareke Young': [0, 0, 0, 4.0, 0], 'Darius Jennings': [3.0, 0, 0, 0, 0], 'Darius Slayton': [166.0, 136.0, 66.0, 123.0, 145.0], 'Darnell Mooney': [0, 143.0, 209.0, 97.0, 74.0], 'Darrius Shepherd': [0.0, 7.0, 0, 0, 0], 'Daurice Fountain': [0, 4.0, 0, 0, 0], 'Davante Adams': [209.0, 354.0, 337.0, 329.0, 258.0], 'David Bell': [0, 0, 0, 39.0, 45.0], 'David Moore': [54.0, 110.0, 0, 0, 18.0], 'David Sills': [0, 0, 3.0, 18.0, 0], 'Davion Davis': [0, 0, 2.0, 0, 0], 'Dax Milne': [0, 0, 14.0, 13.0, 0], 'Daylen Baldwin': [0, 0, 0, 4.0, 0], 'Dazz Newsome': [0, 0, 4.0, 0, 0], "De'Anthony Thomas": [1.0, 0, 0, 0, 0], 'DeAndre Carter': [24.0, 0.0, 74.0, 109.0, 7.0], 'DeAndre Hopkins': [263.0, 283.0, 143.0, 148.0, 216.0], 'DeAndrew White': [8.0, 0, 0, 0, 0], 'DeMichael Harris': [0, 19.0, 0, 0, 0], 'DeSean Jackson': [36.0, 43.0, 71.0, 22.0, 0], 'DeVante Parker': [238.0, 161.0, 100.0, 97.0, 66.0], 'DeVonta Smith': [0, 0, 181.0, 248.0, 220.0], 'Dede Westbrook': [150.0, 0.0, 14.0, 0, 0], 'Deebo Samuel': [180.0, 76.0, 329.0, 161.0, 231.0], 'Demarcus Robinson': [97.0, 101.0, 62.0, 97.0, 85.0], 'Demario Douglas': [0, 0, 0, 0, 101.0], 'Demaryius Thomas': [81.0, 0, 0, 0, 0], 'Dennis Houston': [0, 0, 0, 3.0, 0], 'Denzel Mims': [0, 58.0, 20.0, 27.0, 0], 'Deon Cain': [19.0, 0, 0, 0, 0], 'Deontay Burnett': [6.0, 4.0, 0, 0, 0], 'Deonte Harty': [9.0, 44.0, 107.0, 1.0, 32.0], 'Derius Davis': [0, 0, 0, 0, 25.0], 'Deven Thompkins': [0, 0, 0, 8.0, 31.0], 'Devin Duvernay': [0, 41.0, 75.0, 103.0, 6.0], 'Devin Funchess': [6.0, 0, 0, 0, 0], 'Devin Smith': [21.0, 0, 0, 0, 0], 'Dez Bryant': [0, 21.0, 0, 0, 0], 'Dez Fitzpatrick': [0, 0, 15.0, 0, 0], 'Dezmon Patmon': [0, 0, 9.0, 4.0, 0], 'Diontae Johnson': [150.0, 216.0, 269.0, 172.0, 146.0], 'Diontae Spencer': [6.0, 4.0, -1.0, 0, 0], 'Donovan Peoples-Jones': [0, 56.0, 105.0, 158.0, 24.0], 'Dontayvion Wicks': [0, 0, 0, 0, 115.0], 'Donte Moncrief': [5.0, 2.0, 0, 0, 0], 'Dontrelle Inman': [26.0, 43.0, 0, 0, 0], 'Drake London': [0, 0, 0, 174.0, 166.0], 'Dwayne Harris': [1.0, -1.0, 0, 0, 0], 'Dyami Brown': [0, 0, 26.0, 30.0, 33.0], 'Easop Winston': [0, 0, 1.0, 0, 0], 'Elijah Cooks': [0, 0, 0, 0, 6.0], 'Elijah Moore': [0, 0, 131.0, 83.0, 127.0], 'Emmanuel Sanders': [185.0, 157.0, 125.0, 0, 0], 'Equanimeous St. Brown': [0, 22.0, 19.0, 57.0, 9.0], 'Erik Ezukanma': [0, 0, 0, 1.0, 1.0], 'Frank Darby': [0, 0, 2.0, 2.0, 0], 'Fred Brown': [3.0, 0, 0, 0, 0], 'Freddie Swain': [0, 38.0, 79.0, 10.0, 0], 'Gabriel Davis': [0, 129.0, 120.0, 165.0, 159.0], 'Garrett Wilson': [0, 0, 0, 209.0, 209.0], 'Gehrig Dieter': [0, 2.0, 0, 0, 0], 'George Pickens': [0, 0, 0, 159.0, 200.0], 'Geremy Davis': [6.0, 0, 0, 0, 0], 'Geronimo Allison': [70.0, 0, 0, 0, 0], 'Golden Tate': [149.0, 81.0, 0, 0, 0], 'Greg Dortch': [-1.0, 0, 6.0, 109.0, 60.0], 'Greg Ward': [58.0, 125.0, 32.0, 0, 0], 'Gunner Olszewski': [4.0, 17.0, 4.0, 8.0, -1.0], 'Henry Ruggs': [0, 79.0, 80.0, 0, 0], 'Hunter Renfrow': [128.0, 126.0, 252.0, 75.0, 44.0], 'Ihmir Smith-Marsette': [0, 0, 27.0, 1.0, 24.0], 'Isaiah Ford': [46.0, 51.0, 39.0, 0, 0], 'Isaiah Hodgins': [0, 0, 0, 97.0, 57.0], 'Isaiah McKenzie': [59.0, 88.0, 47.0, 108.0, 15.0], 'Isaiah Wright': [0, 41.0, 0, 0, 0], 'Isaiah Zuber': [0, 5.0, 0, 0, 0], 'Ishmael Hyman': [5.0, 0, 0, 0, 0], 'J.J. Arcega-Whiteside': [29.0, 19.0, 5.0, 0, 0], 'J.J. Koski': [0, 0, -1.0, 0, 0], 'J.J. Nelson': [13.0, 0, 0, 0, 0], "Ja'Marcus Bradley": [0, 11.0, 9.0, 0, 0], "Ja'Marr Chase": [0, 0, 295.0, 238.0, 258.0], 'Jaelon Darden': [0, 0, 10.0, 4.0, 0], 'Jahan Dotson': [0, 0, 0, 127.0, 120.0], 'Jake Bobo': [0, 0, 0, 0, 50.0], 'Jake Kumerow': [35.0, 9.0, 4.0, 10.0, 0], 'Jakeem Grant': [38.0, 75.0, 34.0, 0, 0], 'Jakobi Meyers': [56.0, 138.0, 177.0, 179.0, 212.0], 'Jaleel Scott': [1.0, 2.0, 0, 0, 0], 'Jalen Brooks': [0, 0, 0, 0, 11.0], 'Jalen Camp': [0, 0, 0, 1.0, 0], 'Jalen Guyton': [0, 90.0, 89.0, 8.0, 22.0], 'Jalen Nailor': [0, 0, 0, 31.0, 5.0], 'Jalen Reagor': [0, 76.0, 73.0, 22.0, 20.0], 'Jalen Tolbert': [0, 0, 0, 2.0, 54.0], 'Jalen Virgil': [0, 0, 0, 13.0, 0], 'Jalin Hyatt': [0, 0, 0, 0, 55.0], 'Jamal Agnew': [0.0, 21.0, 64.0, 62.0, 39.0], 'James Proche': [0, 2.0, 33.0, 10.0, -1.0], 'James Washington': [130.0, 94.0, 61.0, 0, 0], 'Jameson Williams': [0, 0, 0, 15.0, 74.0], 'Jamison Crowder': [190.0, 167.0, 106.0, 9.0, 35.0], 'Jarius Wright': [50.0, 0, 0, 0, 0], 'Jaron Brown': [46.0, 0, 0, 0, 0], 'Jarvis Landry': [230.0, 181.0, 128.0, 57.0, 0], 'Jason Brownlee': [0, 0, 0, 0, 15.0], 'Jason Moore': [6.0, 0, 8.0, 1.0, 0], 'Jauan Jennings': [0, 0, 76.0, 77.0, 47.0], 'Javon Wims': [39.0, 14.0, 0, 0, 0], 'Jaxon Smith-Njigba': [0, 0, 0, 0, 144.0], 'Jayden Reed': [0, 0, 0, 0, 207.0], 'Jaydon Mickens': [0, 12.0, 3.0, 0, 0], 'Jaylen Waddle': [0, 0, 240.0, 249.0, 193.0], 'Jeff Smith': [2.0, 30.0, 18.0, 19.0, 0], 'Jerry Jeudy': [0, 152.0, 80.0, 197.0, 136.0], 'Jesus Wilson': [5.0, 0, 0, 0, 0], 'JoJo Natson': [0, 0.0, 0, 0, 0], 'Joe Reed': [0, 7.0, 0, 0, 0], 'John Brown': [213.0, 95.0, 0, 11.0, 0], 'John Franklin III': [1.0, 0, 0, 0, 0], 'John Hightower': [0, 26.0, 0, 0, 0], 'John Metchie': [0, 0, 0, 0, 26.0], 'John Ross': [92.0, 3.0, 37.0, 0, 0], 'John Ursua': [2.0, 0, 0, 0, 0], 'Johnny Holton': [4.0, 0, 0, 0, 0], 'Jonathan Mingo': [0, 0, 0, 0, 79.0], 'Jordan Addison': [0, 0, 0, 0, 214.0], 'Jordan Matthews': [6.0, 0, 0, 0, 0], 'Josh Bellamy': [3.0, 0, 0, 0, 0], 'Josh Downs': [0, 0, 0, 0, 150.0], 'Josh Gordon': [68.0, 0, 12.0, 0, 0], 'Josh Malone': [0, 6.0, 0, 0, 0], 'Josh Palmer': [0, 0, 86.0, 161.0, 103.0], 'Josh Reynolds': [57.0, 118.0, 76.0, 98.0, 124.0], 'JuJu Smith-Schuster': [109.0, 225.0, 33.0, 179.0, 57.0], 'Julian Edelman': [251.0, 52.0, 0, 0, 0], 'Julio Jones': [267.0, 141.0, 74.0, 64.0, 33.0], 'Justin Hardy': [34.0, 0, 0, 0, 0], 'Justin Jefferson': [0, 267.0, 321.0, 358.0, 199.0], 'Justin Watson': [40.0, 15.0, 0, 54.0, 85.0], 'Justyn Ross': [0, 0, 0, 0, 9.0], 'Juwann Winfree': [0, 0, 12.0, 2.0, 0], 'K.J. Hill': [0, 10.0, 6.0, 0, 0], 'K.J. Osborn': [0, 0, 152.0, 145.0, 111.0], 'KJ Hamler': [0, 85.0, 11.0, 23.0, 0], 'KaVontae Turpin': [0, 0, 0, 0.0, 53.0], 'Kadarius Toney': [0, 0, 76.0, 54.0, 47.0], 'Kalif Raymond': [29.0, 26.0, 125.0, 102.0, 90.0], 'Kayshon Boutte': [0, 0, 0, 0, 3.0], 'KeeSean Johnson': [43.0, 28.0, 0, 0, 0], 'Keelan Cole': [74.0, 141.0, 72.0, 29.0, 0], 'Keelan Doss': [22.0, 0, 0, 0, 8.0], 'Keenan Allen': [254.0, 240.0, 251.0, 160.0, 273.0], 'Keith Kirkwood': [0, 2.0, 4.0, 3.0, 13.0], 'Keke Coutee': [49.0, 88.0, 1.0, 2.0, 0], 'Kelvin Harmon': [62.0, 0, 0, 0, 0], 'Kendall Hinton': [0, -4.0, 35.0, 51.0, 0], 'Kendrick Bourne': [91.0, 124.0, 171.0, 81.0, 96.0], 'Kenny Golladay': [242.0, 64.0, 84.0, 19.0, 0], 'Kenny Stills': [113.0, 28.0, 17.0, 0, 0], 'Kevin White': [0, 0, 4.0, 9.0, 0], 'Khadarel Hodge': [10.0, 27.0, 26.0, 37.0, 33.0], 'Khalil Shakir': [0, 0, 0, 31.0, 107.0], 'Kirk Merritt': [0, 0, 2.0, 0, 0], 'Krishawn Hogan': [1.0, 0, 0, 0, 0], 'Kristian Wilkerson': [0, 0, 20.0, 0, 0], 'Kwamie Lassiter': [0, 0, 0, 0, 1.0], 'Kyle Philips': [0, 0, 0, 12.0, 30.0], 'Laquon Treadwell': [31.0, 21.0, 78.0, 9.0, 2.0], 'Larry Fitzgerald': [170.0, 97.0, 0, 0, 0], 'Laviska Shenault': [0, 148.0, 120.0, 65.0, 15.0], 'Lawrence Cager': [0, 5.0, 0, 0, 0], "Lil'Jordan Humphrey": [0, 12.0, 46.0, 3.0, 44.0], 'Lynn Bowden': [0, 49.0, 0, 0, 21.0], 'Mack Hollins': [22.0, 34.0, 59.0, 147.0, 40.0], 'Malik Heath': [0, 0, 0, 0, 29.0], 'Malik Taylor': [0, 16.0, 2.0, 0, 2.0], 'Malik Turner': [42.0, 0, 43.0, 0, 0], 'Marcell Ateman': [14.0, 0, 0, 0, 0], 'Marcus Johnson': [53.0, 36.0, 24.0, 17.0, 0], 'Marcus Kemp': [0, 2.0, 3.0, 0, 0], 'Marqise Lee': [3.0, 0, 0, 0, 0], 'Marquez Callaway': [0, 40.0, 145.0, 35.0, 0], 'Marquez Valdes-Scantling': [76.0, 131.0, 83.0, 117.0, 52.0], 'Marquise Brown': [141.0, 176.0, 220.0, 149.0, 128.0], 'Marquise Goodwin': [35.0, 0, 54.0, 85.0, 12.0], 'Marvin Hall': [35.0, 56.0, 2.0, 0, 0], 'Marvin Jones': [188.0, 220.0, 174.0, 110.0, 6.0], 'Marvin Mims': [0, 0, 0, 0, 62.0], 'Mason Kinsey': [0, 0, 0, 1.0, 1.0], 'Maurice Alexander': [0, 0, 0, 1.0, 0], 'Maurice Ffrench': [0, 0, 0.0, 0, 0], 'Mecole Hardman': [108.0, 118.0, 134.0, 89.0, 24.0], 'Michael Bandy': [0, 0, 0, 17.0, 0], 'Michael Crabtree': [5.0, 0, 0, 0, 0], 'Michael Gallup': [204.0, 166.0, 88.0, 100.0, 83.0], 'Michael Pittman': [0, 91.0, 228.0, 212.0, 243.0], 'Michael Thomas': [368.0, 81.0, 0, 49.0, 86.0], 'Michael Walker': [0.0, 0, 0, 0, 0], 'Michael Wilson': [0, 0, 0, 0, 108.0], 'Michael Woods': [0, 0, 0, 7.0, 0], 'Mike Evans': [228.0, 243.0, 254.0, 220.0, 276.0], 'Mike Strachan': [0, 0, 4.0, 8.0, 5.0], 'Mike Thomas': [2.0, 28.0, 8.0, 7.0, 0], 'Mike Williams': [154.0, 146.0, 239.0, 171.0, 49.0], 'Miles Boykin': [47.0, 64.0, 1.0, 3.0, 3.0], 'Mohamed Sanu': [117.0, 40.0, 28.0, 0, 0], 'Montrell Washington': [0, 0, 0, 4.0, 0], "N'Keal Harry": [35.0, 70.0, 26.0, 21.0, 0], 'Nathaniel Dell': [0, 0, 0, 0, 159.0], 'Nelson Agholor': [92.0, 177.0, 99.0, 73.0, 92.0], 'Nick Westbrook': [0, 6.0, 102.0, 78.0, 78.0], 'Nico Collins': [0, 0, 76.0, 92.0, 254.0], 'Noah Brown': [0, 26.0, 30.0, 110.0, 98.0], 'Nsimba Webster': [0, -1.0, 0, 3.0, 0], 'Odell Beckham Jr.': [195.0, 83.0, 120.0, 0, 102.0], 'Olabisi Johnson': [72.0, 32.0, 0, 0, 0], 'Olamide Zaccheaus': [20.0, 52.0, 84.0, 103.0, 34.0], 'Parker Washington': [0, 0, 0, 0, 38.0], 'Parris Campbell': [36.0, 13.0, 30.0, 141.0, 28.0], 'Paul Richardson': [61.0, 0, 0, 0, 0], 'Penny Hart': [0, 2.0, 10.0, 4.0, 0], 'Pharoh Cooper': [49.0, 11.0, 6.0, 2.0, 0], 'Phillip Dorsett': [96.0, 0, 16.0, 46.0, 0], 'Preston Williams': [89.0, 71.0, 12.0, 0, 0], 'Puka Nacua': [0, 0, 0, 0, 288.0], 'Quentin Johnston': [0, 0, 0, 0, 86.0], 'Quez Watkins': [0, 22.0, 108.0, 79.0, 33.0], 'Quincy Enunwa': [0.0, 0, 0, 0, 0], 'Quintez Cephus': [0, 62.0, 47.0, 3.0, 0], 'Racey McMath': [0, 0, 1.0, 5.0, 0], 'Rakim Jarrett': [0, 0, 0, 0, 8.0], 'Randall Cobb': [150.0, 95.0, 91.0, 76.0, 15.0], 'Rashard Davis': [2.0, 0, 0, 0, 0], 'Rashard Higgins': [14.0, 115.0, 52.0, 0, 0], 'Rashee Rice': [0, 0, 0, 0, 207.0], 'Rashid Shaheed': [0, 0, 0, 94.0, 142.0], 'Rashod Bateman': [0, 0, 99.0, 51.0, 68.0], 'Ray Ray McCloud': [-1.0, 30.0, 62.0, 54.0, 26.0], 'Richie James': [25.0, 63.0, 0, 129.0, 17.0], 'Rico Gafford': [13.0, 0, 0, 0, 0], 'Riley Ridley': [12.0, 7.0, 0, 0, 0], 'River Cracraft': [0, 9.0, 0, 29.0, 25.0], 'Robbie Chosen': [156.0, 217.0, 131.0, 51.0, 20.0], 'Robert Davis': [3.0, 0, 0, 0, 0], 'Robert Foster': [11.0, 4.0, 0, 0, 0], 'Robert Woods': [220.0, 236.0, 131.0, 109.0, 84.0], 'Romeo Doubs': [0, 0, 0, 97.0, 168.0], 'Rondale Moore': [0, 0, 100.0, 86.0, 95.0], 'Ronnie Bell': [0, 0, 0, 0, 29.0], 'Russell Gage': [92.0, 176.0, 160.0, 119.0, 0], 'Russell Shepard': [4.0, 0, 0, 0, 0], 'Ryan Grant': [5.0, 0, 0, 0, 0], 'Ryan Switzer': [10.0, 0, 0, 0, 0], 'Sammy Watkins': [132.0, 85.0, 65.0, 43.0, 0], 'Samori Toure': [0, 0, 0, 17.0, 15.0], 'Scott Miller': [37.0, 96.0, 17.0, 37.0, 36.0], 'Seth Roberts': [54.0, 6.0, 0, 0, 0], 'Seth Williams': [0, 0, 4.0, 0, 0], 'Shi Smith': [0, 0, 16.0, 58.0, 0], 'Simi Fehoko': [0, 0, 0, 5.0, 7.0], 'Skyy Moore': [0, 0, 0, 42.0, 49.0], 'Stanley Morgan': [3.0, 0, 2.0, 0, 0], 'Stefon Diggs': [205.0, 320.0, 279.0, 309.0, 267.0], 'Sterling Shepard': [136.0, 154.0, 75.0, 33.0, 17.0], 'Steven Mitchell': [5.0, 10.0, 0, 0, 0], 'Steven Sims': [98.0, 54.0, 0, 27.0, 5.0], 'T.J. Jones': [12.0, 0, 0, 0, 0], 'T.Y. Hilton': [120.0, 158.0, 69.0, 18.0, 0], 'Tajae Sharpe': [77.0, 0, 43.0, 0, 0], 'Tarik Black': [0, 0, 2.0, 0, 0], 'Tavon Austin': [42.0, 4.0, 47.0, 0, 0], 'Taylor Gabriel': [84.0, 0, 0, 0, 0], 'Ted Ginn Jr.': [80.0, 6.0, 0, 0, 0], 'Tee Higgins': [0, 187.0, 214.0, 214.0, 133.0], 'Terrace Marshall': [0, 0, 28.0, 78.0, 30.0], 'Terry Godwin': [0, 6.0, 0, 0, 0], 'Terry McLaurin': [186.0, 218.0, 208.0, 220.0, 205.0], 'Tevin Jones': [8.0, 0, 0, 0, 0], 'Tim Jones': [0, 0, 0, 5.0, 17.0], 'Tim Patrick': [35.0, 154.0, 147.0, 0, 0], 'Tom Kennedy': [0, 0, 18.0, 20.0, 0], 'Tommylee Lewis': [0, 2.0, 1.0, 0, 0], 'Travis Benjamin': [8.0, 0, -1.0, 0, 0], 'Travis Fulgham': [0, 110.0, 0, 0, 0], 'Tre Tucker': [0, 0, 0, 0, 65.0], "Tre'Quan Smith": [67.0, 98.0, 84.0, 48.0, 0], 'Trent Sherfield': [10.0, 9.0, 20.0, 76.0, 21.0], 'Trent Taylor': [0, 16.0, 6.0, 10.0, -1.0], 'Trenton Irwin': [0, 1.0, 4.0, 59.0, 58.0], 'Trevor Davis': [28.0, 0, 0, 0, 0], 'Trey Palmer': [0, 0, 0, 0, 89.0], 'Trey Quinn': [48.0, 0, 0, 0, 0], 'Treylon Burks': [0, 0, 0, 88.0, 35.0], 'Trinity Benson': [0, 0, 18.0, 0, 0], 'Trishton Jackson': [0, 0, 0, 0, 4.0], 'Ty Montgomery': [26.0, 15.0, 26.0, 10.0, 6.0], 'Tylan Wallace': [0, 0, 3.0, 5.0, 2.0], 'Tyler Boyd': [217.0, 186.0, 173.0, 160.0, 135.0], 'Tyler Johnson': [0, 38.0, 66.0, 0, 8.0], 'Tyler Lockett': [231.0, 260.0, 234.0, 231.0, 197.0], 'Tyler Scott': [0, 0, 0, 0, 31.0], 'Tyquan Thornton': [0, 0, 0, 60.0, 21.0], 'Tyreek Hill': [182.0, 317.0, 286.0, 338.0, 370.0], 'Tyrell Williams': [136.0, 0, 3.0, 0, 0], 'Tyrie Cleveland': [0, 11.0, 0, 4.0, 0], 'Tyron Johnson': [0, 76.0, 3.0, 1.0, 0], 'Van Jefferson': [0, 43.0, 162.0, 74.0, 35.0], 'Velus Jones': [0, 0, 0, 32.0, 9.0], 'Ventell Bryant': [8.0, 0, 0, 0, 0], 'Vyncint Smith': [46.0, 2.0, 0, 0, 0], "Wan'Dale Robinson": [0, 0, 0, 50.0, 124.0], 'Will Fuller': [130.0, 185.0, 8.0, 0, 0], 'Willie Snead': [90.0, 89.0, 6.0, 0, 2.0], 'Xavier Gipson': [0, 0, 0, 0, 46.0], 'Xavier Hutchinson': [0, 0, 0, 0, 16.0], 'Zach Pascal': [128.0, 129.0, 87.0, 30.0, 5.0], 'Zay Flowers': [0, 0, 0, 0, 197.0], 'Zay Jones': [43.0, 32.0, 101.0, 190.0, 74.0]}

In [110]:
for index, row in player_predictions.iterrows():
    player = row['Player']
    predicted_points = row['Predicted_Fantasy_Points_2024']
    if player in name_fantasy_dict:
        name_fantasy_dict[player].append(predicted_points)
   

print(name_fantasy_dict)

{'A.J. Brown': [210.0, 237.0, 174.0, 293.0, 283.0, 299.23], 'A.J. Green': [0, 107.0, 150.0, 58.0, 0, 144.51], 'A.T. Perry': [0, 0, 0, 0, 57.0, 51.14], 'Adam Humphries': [83.0, 54.0, 73.0, 0, 0, 79.91], 'Adam Thielen': [110.0, 246.0, 195.0, 171.0, 223.0, 186.99], 'Albert Wilson': [81.0, 0, 43.0, 0, 0, 44.19], 'Alec Pierce': [0, 0, 0, 107.0, 90.0, 107.55], 'Alex Bachman': [0, 0, 0.0, 0, 0, -0.65], 'Alex Erickson': [90.0, 19.0, 7.0, 0, 41.0, 48.19], 'Alexander Hollins': [6.0, 0, 0, 0, 0, 9.03], 'Allen Hurns': [79.0, 0, 0, 0, 0, 86.92], 'Allen Lazard': [97.0, 92.0, 136.0, 167.0, 55.0, 101.95], 'Allen Robinson': [248.0, 258.0, 82.0, 81.0, 56.0, 84.29], 'Alshon Jeffery': [117.0, 22.0, 0, 0, 0, 23.56], 'Amari Cooper': [238.0, 232.0, 195.0, 240.0, 219.0, 235.54], 'Amari Rodgers': [0, 0, 7.0, 37.0, 0, 42.3], 'Amon-Ra St. Brown': [0, 0, 219.0, 255.0, 324.0, 468.82], 'Andre Baccellia': [0, 0, 0, 9.0, 0, 8.82], 'Andre Patton': [9.0, 0, 0, 0, 0, 11.14], 'Andre Roberts': [3.0, 4.0, 2.0, 0, 0, 6.57], 'Andrei Iosivas': [0, 0, 0, 0, 46.0, 23.77], 'Andy Isabella': [31.0, 51.0, 2.0, 4.0, 0, 16.67], 'Anthony Miller': [123.0, 101.0, 14.0, 0, 0, -97.87], 'Anthony Schwartz': [0, 0, 30.0, 17.0, 0, 10.09], 'Antoine Green': [0, 0, 0, 0, 1.0, -0.23], 'Antoine Wesley': [0, 0, 54.0, 0, 0, 43.14], 'Antonio Brown': [15.0, 113.0, 118.0, 0, 0, 103.74], 'Antonio Callaway': [16.0, 3.0, 0, 0, 0, 3.56], 'Antonio Gandy-Golden': [0, 3.0, 0, 0, 0, -0.02], 'Ashton Dulin': [3.0, 7.0, 42.0, 37.0, 0, 39.36], 'Auden Tate': [97.0, 26.0, 11.0, 0, 0, 15.2], 'Austin Carr': [1.0, 11.0, 0, 0, 0, 5.03], 'Austin Mack': [0, 14.0, 0, 0, 0, 18.51], 'Austin Trammell': [0, 0, 0, 2.0, 5.0, 5.45], 'Bennett Skowronek': [0, 0, 22.0, 79.0, 21.0, 17.01], 'Bennie Fowler': [44.0, 3.0, 0, 0, 0, 1.67], 'Bo Melton': [0, 0, 0, 0, 43.0, 45.24], 'Brandin Cooks': [109.0, 226.0, 223.0, 139.0, 163.0, 138.12], 'Brandon Aiyuk': [0, 179.0, 162.0, 220.0, 241.0, 415.12], 'Brandon Johnson': [0, 0, 0, 15.0, 69.0, 59.14], 'Brandon Powell': [0, 25.0, 0, 41.0, 63.0, 67.56], 'Brandon Zylstra': [17.0, 5.0, 45.0, 0, 0, 51.2], 'Braxton Berrios': [14.0, 91.0, 109.0, 52.0, 53.0, 54.46], 'Braylon Sanders': [0, 0, 0, 2.0, 0, 2.93], 'Breshad Perriman': [134.0, 94.0, 31.0, 23.0, 0, 34.78], 'Britain Covey': [0, 0, 0, 0, 7.0, 8.19], 'Bryan Edwards': [0, 33.0, 104.0, 4.0, 0, 113.88], 'Byron Pringle': [32.0, 33.0, 121.0, 33.0, 25.0, 49.78], 'C.J. Board': [4.0, 18.0, 7.0, 1.0, 0, 8.65], 'C.J. Saunders': [0, 0, 3.0, 0, 0, 1.67], 'Cade Johnson': [0, 0, 0, 4.0, 0, 3.77], 'Calvin Austin': [0, 0, 0, 0, 47.0, 37.24], 'Calvin Ridley': [190.0, 278.0, 70.0, 0, 223.0, 213.23], 'Cam Sims': [4.0, 82.0, 44.0, 14.0, 0, 45.97], 'Cameron Batson': [0, 26.0, 10.0, 0, 0, 2.51], 'Cedric Tillman': [0, 0, 0, 0, 40.0, 46.51], 'Cedrick Wilson': [9.0, 51.0, 139.0, 23.0, 66.0, 53.3], 'CeeDee Lamb': [0, 201.0, 225.0, 293.0, 392.0, 539.21], 'Chad Beebe': [8.0, 48.0, 0, 0, 0, 41.66], 'Chad Hansen': [0, 44.0, 0, 0, 0, 49.03], 'Charlie Jones': [0, 0, 0, 0, 13.0, 12.82], 'Chase Claypool': [0, 207.0, 159.0, 100.0, 19.0, -14.07], 'Chatarius Atwell': [0, 0, 0, 60.0, 105.0, 101.03], 'Chester Rogers': [43.0, 0, 60.0, -1.0, 0, -0.65], 'Chris Conley': [148.0, 91.0, 62.0, 7.0, 9.0, -18.46], 'Chris Godwin': [272.0, 185.0, 237.0, 219.0, 200.0, 215.72], 'Chris Hogan': [12.0, 25.0, 13.0, 0, 0, 12.44], 'Chris Lacy': [8.0, 0, 0, 0, 0, 11.98], 'Chris Moore': [4.0, 0, 53.0, 111.0, 61.0, 88.61], 'Chris Olave': [0, 0, 0, 196.0, 223.0, 235.76], 'Christian Blake': [18.0, 24.0, 5.0, 0, 0, 18.27], 'Christian Kirk': [157.0, 139.0, 199.0, 235.0, 145.0, 169.4], 'Christian Watson': [0, 0, 0, 155.0, 98.0, 88.19], 'Cody Core': [5.0, 0, 0, 0, 0, 5.24], 'Cody Hollister': [3.0, 2.0, 6.0, 8.0, 0, 12.37], 'Cody Latimer': [62.0, 0, 0, 0, 0, 62.5], 'Cody Thompson': [0, 0, 0, 0, 2.0, 1.45], 'Cody White': [0, 0, 7.0, 1.0, 0, -0.23], 'Cole Beasley': [178.0, 203.0, 153.0, 7.0, 0, -194.55], 'Collin Johnson': [0, 55.0, 20.0, 0, 2.0, 1.67], 'Colton Dowell': [0, 0, 0, 0, 1.0, -0.02], 'Cooper Kupp': [265.0, 203.0, 430.0, 197.0, 158.0, 229.01], 'Corey Davis': [108.0, 187.0, 102.0, 91.0, 0, 136.19], 'Courtland Sutton': [215.0, 9.0, 141.0, 154.0, 187.0, 145.49], 'Curtis Samuel': [162.0, 199.0, 7.0, 166.0, 149.0, 114.85], 'Cyril Grayson': [1.0, 0, 44.0, 0, 0, 43.98], "D'Wayne Eskridge": [0, 0, 26.0, 11.0, 1.0, -1.78], "D'haquille Williams": [32.0, 0, 0, 0, 0, 34.3], 'D.J. Chark': [218.0, 148.0, 32.0, 93.0, 108.0, 123.38], 'D.J. Montgomery': [0, 0, 6.0, 0, 13.0, 11.14], 'D.J. Moore': [225.0, 205.0, 229.0, 189.0, 280.0, 251.97], 'D.J. Turner': [0, 0, 0, 2.0, 0, -0.65], 'D.K. Metcalf': [182.0, 266.0, 237.0, 222.0, 218.0, 229.43], "Da'Mari Scott": [4.0, 0, 0, 0, 0, 3.98], 'DaeSean Hamilton': [59.0, 58.0, 0, 0, 0, 61.03], 'Damiere Byrd': [69.0, 107.0, 62.0, 48.0, 0, 80.12], 'Damion Ratley': [36.0, 9.0, 0, 0, 0, 12.61], 'Damion Willis': [15.0, 0, 0, 0, 0, 16.61], 'Danny Amendola': [135.0, 101.0, 65.0, 0, 0, 18.01], 'Danny Gray': [0, 0, 0, 2.0, 0, 1.45], 'Dante Pettis': [32.0, 16.0, 23.0, 59.0, 0, 60.76], 'Dareke Young': [0, 0, 0, 4.0, 0, 4.4], 'Darius Jennings': [3.0, 0, 0, 0, 0, 2.93], 'Darius Slayton': [166.0, 136.0, 66.0, 123.0, 145.0, 138.03], 'Darnell Mooney': [0, 143.0, 209.0, 97.0, 74.0, 129.5], 'Darrius Shepherd': [0.0, 7.0, 0, 0, 0, 9.03], 'Daurice Fountain': [0, 4.0, 0, 0, 0, 4.19], 'Davante Adams': [209.0, 354.0, 337.0, 329.0, 258.0, 77.85], 'David Bell': [0, 0, 0, 39.0, 45.0, 34.51], 'David Moore': [54.0, 110.0, 0, 0, 18.0, 19.14], 'David Sills': [0, 0, 3.0, 18.0, 0, 21.66], 'Davion Davis': [0, 0, 2.0, 0, 0, 2.93], 'Dax Milne': [0, 0, 14.0, 13.0, 0, 7.14], 'Daylen Baldwin': [0, 0, 0, 4.0, 0, 4.61], 'Dazz Newsome': [0, 0, 4.0, 0, 0, 4.19], "De'Anthony Thomas": [1.0, 0, 0, 0, 0, 0.61], 'DeAndre Carter': [24.0, 0.0, 74.0, 109.0, 7.0, 42.78], 'DeAndre Hopkins': [263.0, 283.0, 143.0, 148.0, 216.0, 203.72], 'DeAndrew White': [8.0, 0, 0, 0, 0, 10.09], 'DeMichael Harris': [0, 19.0, 0, 0, 0, 15.98], 'DeSean Jackson': [36.0, 43.0, 71.0, 22.0, 0, 53.83], 'DeVante Parker': [238.0, 161.0, 100.0, 97.0, 66.0, 52.48], 'DeVonta Smith': [0, 0, 181.0, 248.0, 220.0, 223.79], 'Dede Westbrook': [150.0, 0.0, 14.0, 0, 0, 50.16], 'Deebo Samuel': [180.0, 76.0, 329.0, 161.0, 231.0, 187.12], 'Demarcus Robinson': [97.0, 101.0, 62.0, 97.0, 85.0, 82.75], 'Demario Douglas': [0, 0, 0, 0, 101.0, 117.45], 'Demaryius Thomas': [81.0, 0, 0, 0, 0, 90.5], 'Dennis Houston': [0, 0, 0, 3.0, 0, 2.72], 'Denzel Mims': [0, 58.0, 20.0, 27.0, 0, 46.58], 'Deon Cain': [19.0, 0, 0, 0, 0, 25.45], 'Deontay Burnett': [6.0, 4.0, 0, 0, 0, 3.35], 'Deonte Harty': [9.0, 44.0, 107.0, 1.0, 32.0, 39.5], 'Derius Davis': [0, 0, 0, 0, 25.0, 13.24], 'Deven Thompkins': [0, 0, 0, 8.0, 31.0, 16.82], 'Devin Duvernay': [0, 41.0, 75.0, 103.0, 6.0, 39.54], 'Devin Funchess': [6.0, 0, 0, 0, 0, 6.09], 'Devin Smith': [21.0, 0, 0, 0, 0, 23.14], 'Dez Bryant': [0, 21.0, 0, 0, 0, 9.24], 'Dez Fitzpatrick': [0, 0, 15.0, 0, 0, 9.67], 'Dezmon Patmon': [0, 0, 9.0, 4.0, 0, 4.4], 'Diontae Johnson': [150.0, 216.0, 269.0, 172.0, 146.0, 156.32], 'Diontae Spencer': [6.0, 4.0, -1.0, 0, 0, -2.99], 'Donovan Peoples-Jones': [0, 56.0, 105.0, 158.0, 24.0, 99.03], 'Dontayvion Wicks': [0, 0, 0, 0, 115.0, 121.66], 'Donte Moncrief': [5.0, 2.0, 0, 0, 0, 2.51], 'Dontrelle Inman': [26.0, 43.0, 0, 0, 0, 33.66], 'Drake London': [0, 0, 0, 174.0, 166.0, 189.87], 'Dwayne Harris': [1.0, -1.0, 0, 0, 0, -0.65], 'Dyami Brown': [0, 0, 26.0, 30.0, 33.0, 34.7], 'Easop Winston': [0, 0, 1.0, 0, 0, 0.4], 'Elijah Cooks': [0, 0, 0, 0, 6.0, 7.35], 'Elijah Moore': [0, 0, 131.0, 83.0, 127.0, 134.06], 'Emmanuel Sanders': [185.0, 157.0, 125.0, 0, 0, 83.06], 'Equanimeous St. Brown': [0, 22.0, 19.0, 57.0, 9.0, 28.43], 'Erik Ezukanma': [0, 0, 0, 1.0, 1.0, -0.65], 'Frank Darby': [0, 0, 2.0, 2.0, 0, 2.51], 'Fred Brown': [3.0, 0, 0, 0, 0, 3.77], 'Freddie Swain': [0, 38.0, 79.0, 10.0, 0, 67.75], 'Gabriel Davis': [0, 129.0, 120.0, 165.0, 159.0, 156.4], 'Garrett Wilson': [0, 0, 0, 209.0, 209.0, 218.71], 'Gehrig Dieter': [0, 2.0, 0, 0, 0, 1.45], 'George Pickens': [0, 0, 0, 159.0, 200.0, 239.34], 'Geremy Davis': [6.0, 0, 0, 0, 0, 7.35], 'Geronimo Allison': [70.0, 0, 0, 0, 0, 59.77], 'Golden Tate': [149.0, 81.0, 0, 0, 0, 81.03], 'Greg Dortch': [-1.0, 0, 6.0, 109.0, 60.0, 58.29], 'Greg Ward': [58.0, 125.0, 32.0, 0, 0, 52.82], 'Gunner Olszewski': [4.0, 17.0, 4.0, 8.0, -1.0, -0.65], 'Henry Ruggs': [0, 79.0, 80.0, 0, 0, 98.08], 'Hunter Renfrow': [128.0, 126.0, 252.0, 75.0, 44.0, 108.54], 'Ihmir Smith-Marsette': [0, 0, 27.0, 1.0, 24.0, 9.88], 'Isaiah Ford': [46.0, 51.0, 39.0, 0, 0, 47.21], 'Isaiah Hodgins': [0, 0, 0, 97.0, 57.0, 47.77], 'Isaiah McKenzie': [59.0, 88.0, 47.0, 108.0, 15.0, 24.83], 'Isaiah Wright': [0, 41.0, 0, 0, 0, 40.82], 'Isaiah Zuber': [0, 5.0, 0, 0, 0, 5.45], 'Ishmael Hyman': [5.0, 0, 0, 0, 0, 6.51], 'J.J. Arcega-Whiteside': [29.0, 19.0, 5.0, 0, 0, -6.22], 'J.J. Koski': [0, 0, -1.0, 0, 0, -0.65], 'J.J. Nelson': [13.0, 0, 0, 0, 0, 6.93], "Ja'Marcus Bradley": [0, 11.0, 9.0, 0, 0, 12.82], "Ja'Marr Chase": [0, 0, 295.0, 238.0, 258.0, 253.24], 'Jaelon Darden': [0, 0, 10.0, 4.0, 0, 4.82], 'Jahan Dotson': [0, 0, 0, 127.0, 120.0, 108.4], 'Jake Bobo': [0, 0, 0, 0, 50.0, 40.61], 'Jake Kumerow': [35.0, 9.0, 4.0, 10.0, 0, 19.86], 'Jakeem Grant': [38.0, 75.0, 34.0, 0, 0, 29.15], 'Jakobi Meyers': [56.0, 138.0, 177.0, 179.0, 212.0, 185.73], 'Jaleel Scott': [1.0, 2.0, 0, 0, 0, 2.72], 'Jalen Brooks': [0, 0, 0, 0, 11.0, 12.82], 'Jalen Camp': [0, 0, 0, 1.0, 0, 0.82], 'Jalen Guyton': [0, 90.0, 89.0, 8.0, 22.0, 18.09], 'Jalen Nailor': [0, 0, 0, 31.0, 5.0, 5.45], 'Jalen Reagor': [0, 76.0, 73.0, 22.0, 20.0, 33.47], 'Jalen Tolbert': [0, 0, 0, 2.0, 54.0, 55.77], 'Jalen Virgil': [0, 0, 0, 13.0, 0, 15.14], 'Jalin Hyatt': [0, 0, 0, 0, 55.0, 77.87], 'Jamal Agnew': [0.0, 21.0, 64.0, 62.0, 39.0, 47.84], 'James Proche': [0, 2.0, 33.0, 10.0, -1.0, 14.45], 'James Washington': [130.0, 94.0, 61.0, 0, 0, 66.75], 'Jameson Williams': [0, 0, 0, 15.0, 74.0, 73.87], 'Jamison Crowder': [190.0, 167.0, 106.0, 9.0, 35.0, 49.13], 'Jarius Wright': [50.0, 0, 0, 0, 0, 61.66], 'Jaron Brown': [46.0, 0, 0, 0, 0, 45.66], 'Jarvis Landry': [230.0, 181.0, 128.0, 57.0, 0, -146.0], 'Jason Brownlee': [0, 0, 0, 0, 15.0, 11.14], 'Jason Moore': [6.0, 0, 8.0, 1.0, 0, 0.4], 'Jauan Jennings': [0, 0, 76.0, 77.0, 47.0, 55.6], 'Javon Wims': [39.0, 14.0, 0, 0, 0, 9.45], 'Jaxon Smith-Njigba': [0, 0, 0, 0, 144.0, 131.55], 'Jayden Reed': [0, 0, 0, 0, 207.0, 166.29], 'Jaydon Mickens': [0, 12.0, 3.0, 0, 0, 1.45], 'Jaylen Waddle': [0, 0, 240.0, 249.0, 193.0, 212.81], 'Jeff Smith': [2.0, 30.0, 18.0, 19.0, 0, 24.72], 'Jerry Jeudy': [0, 152.0, 80.0, 197.0, 136.0, 158.95], 'Jesus Wilson': [5.0, 0, 0, 0, 0, 6.72], 'JoJo Natson': [0, 0.0, 0, 0, 0, -0.65], 'Joe Reed': [0, 7.0, 0, 0, 0, -0.65], 'John Brown': [213.0, 95.0, 0, 11.0, 0, 8.19], 'John Franklin III': [1.0, 0, 0, 0, 0, -0.65], 'John Hightower': [0, 26.0, 0, 0, 0, 34.51], 'John Metchie': [0, 0, 0, 0, 26.0, 32.61], 'John Ross': [92.0, 3.0, 37.0, 0, 0, 44.63], 'John Ursua': [2.0, 0, 0, 0, 0, 1.67], 'Johnny Holton': [4.0, 0, 0, 0, 0, 2.93], 'Jonathan Mingo': [0, 0, 0, 0, 79.0, 87.35], 'Jordan Addison': [0, 0, 0, 0, 214.0, 191.13], 'Jordan Matthews': [6.0, 0, 0, 0, 0, 6.3], 'Josh Bellamy': [3.0, 0, 0, 0, 0, 3.56], 'Josh Downs': [0, 0, 0, 0, 150.0, 161.66], 'Josh Gordon': [68.0, 0, 12.0, 0, 0, 6.09], 'Josh Malone': [0, 6.0, 0, 0, 0, 2.72], 'Josh Palmer': [0, 0, 86.0, 161.0, 103.0, 121.7], 'Josh Reynolds': [57.0, 118.0, 76.0, 98.0, 124.0, 114.61], 'JuJu Smith-Schuster': [109.0, 225.0, 33.0, 179.0, 57.0, 75.99], 'Julian Edelman': [251.0, 52.0, 0, 0, 0, 65.66], 'Julio Jones': [267.0, 141.0, 74.0, 64.0, 33.0, -77.17], 'Justin Hardy': [34.0, 0, 0, 0, 0, 40.4], 'Justin Jefferson': [0, 267.0, 321.0, 358.0, 199.0, 299.0], 'Justin Watson': [40.0, 15.0, 0, 54.0, 85.0, 96.19], 'Justyn Ross': [0, 0, 0, 0, 9.0, 10.51], 'Juwann Winfree': [0, 0, 12.0, 2.0, 0, 2.93], 'K.J. Hill': [0, 10.0, 6.0, 0, 0, 5.67], 'K.J. Osborn': [0, 0, 152.0, 145.0, 111.0, 112.07], 'KJ Hamler': [0, 85.0, 11.0, 23.0, 0, 41.02], 'KaVontae Turpin': [0, 0, 0, 0.0, 53.0, 26.09], 'Kadarius Toney': [0, 0, 76.0, 54.0, 47.0, 42.98], 'Kalif Raymond': [29.0, 26.0, 125.0, 102.0, 90.0, 104.34], 'Kayshon Boutte': [0, 0, 0, 0, 3.0, 3.35], 'KeeSean Johnson': [43.0, 28.0, 0, 0, 0, 35.77], 'Keelan Cole': [74.0, 141.0, 72.0, 29.0, 0, 23.26], 'Keelan Doss': [22.0, 0, 0, 0, 8.0, 6.3], 'Keenan Allen': [254.0, 240.0, 251.0, 160.0, 273.0, 248.16], 'Keith Kirkwood': [0, 2.0, 4.0, 3.0, 13.0, 8.88], 'Keke Coutee': [49.0, 88.0, 1.0, 2.0, 0, 31.14], 'Kelvin Harmon': [62.0, 0, 0, 0, 0, 76.19], 'Kendall Hinton': [0, -4.0, 35.0, 51.0, 0, 130.49], 'Kendrick Bourne': [91.0, 124.0, 171.0, 81.0, 96.0, 92.3], 'Kenny Golladay': [242.0, 64.0, 84.0, 19.0, 0, 110.11], 'Kenny Stills': [113.0, 28.0, 17.0, 0, 0, 17.09], 'Kevin White': [0, 0, 4.0, 9.0, 0, 14.93], 'Khadarel Hodge': [10.0, 27.0, 26.0, 37.0, 33.0, 57.27], 'Khalil Shakir': [0, 0, 0, 31.0, 107.0, 127.97], 'Kirk Merritt': [0, 0, 2.0, 0, 0, 2.09], 'Krishawn Hogan': [1.0, 0, 0, 0, 0, 0.19], 'Kristian Wilkerson': [0, 0, 20.0, 0, 0, 8.19], 'Kwamie Lassiter': [0, 0, 0, 0, 1.0, -0.23], 'Kyle Philips': [0, 0, 0, 12.0, 30.0, 37.45], 'Laquon Treadwell': [31.0, 21.0, 78.0, 9.0, 2.0, 28.88], 'Larry Fitzgerald': [170.0, 97.0, 0, 0, 0, 85.45], 'Laviska Shenault': [0, 148.0, 120.0, 65.0, 15.0, 14.95], 'Lawrence Cager': [0, 5.0, 0, 0, 0, 6.72], "Lil'Jordan Humphrey": [0, 12.0, 46.0, 3.0, 44.0, 33.4], 'Lynn Bowden': [0, 49.0, 0, 0, 21.0, 16.82], 'Mack Hollins': [22.0, 34.0, 59.0, 147.0, 40.0, 58.78], 'Malik Heath': [0, 0, 0, 0, 29.0, 25.66], 'Malik Taylor': [0, 16.0, 2.0, 0, 2.0, 2.09], 'Malik Turner': [42.0, 0, 43.0, 0, 0, 30.72], 'Marcell Ateman': [14.0, 0, 0, 0, 0, 23.77], 'Marcus Johnson': [53.0, 36.0, 24.0, 17.0, 0, 19.01], 'Marcus Kemp': [0, 2.0, 3.0, 0, 0, 4.4], 'Marqise Lee': [3.0, 0, 0, 0, 0, 3.14], 'Marquez Callaway': [0, 40.0, 145.0, 35.0, 0, 150.19], 'Marquez Valdes-Scantling': [76.0, 131.0, 83.0, 117.0, 52.0, 67.06], 'Marquise Brown': [141.0, 176.0, 220.0, 149.0, 128.0, 138.63], 'Marquise Goodwin': [35.0, 0, 54.0, 85.0, 12.0, 13.45], 'Marvin Hall': [35.0, 56.0, 2.0, 0, 0, 34.92], 'Marvin Jones': [188.0, 220.0, 174.0, 110.0, 6.0, -158.88], 'Marvin Mims': [0, 0, 0, 0, 62.0, 78.71], 'Mason Kinsey': [0, 0, 0, 1.0, 1.0, 0.61], 'Maurice Alexander': [0, 0, 0, 1.0, 0, 0.82], 'Maurice Ffrench': [0, 0, 0.0, 0, 0, -0.65], 'Mecole Hardman': [108.0, 118.0, 134.0, 89.0, 24.0, 26.99], 'Michael Bandy': [0, 0, 0, 17.0, 0, 18.09], 'Michael Crabtree': [5.0, 0, 0, 0, 0, 3.98], 'Michael Gallup': [204.0, 166.0, 88.0, 100.0, 83.0, 73.82], 'Michael Pittman': [0, 91.0, 228.0, 212.0, 243.0, 241.85], 'Michael Thomas': [368.0, 81.0, 0, 49.0, 86.0, 93.66], 'Michael Walker': [0.0, 0, 0, 0, 0, 2.51], 'Michael Wilson': [0, 0, 0, 0, 108.0, 118.29], 'Michael Woods': [0, 0, 0, 7.0, 0, 8.82], 'Mike Evans': [228.0, 243.0, 254.0, 220.0, 276.0, 280.32], 'Mike Strachan': [0, 0, 4.0, 8.0, 5.0, 8.92], 'Mike Thomas': [2.0, 28.0, 8.0, 7.0, 0, 13.39], 'Mike Williams': [154.0, 146.0, 239.0, 171.0, 49.0, 146.74], 'Miles Boykin': [47.0, 64.0, 1.0, 3.0, 3.0, 13.95], 'Mohamed Sanu': [117.0, 40.0, 28.0, 0, 0, 57.71], 'Montrell Washington': [0, 0, 0, 4.0, 0, -0.23], "N'Keal Harry": [35.0, 70.0, 26.0, 21.0, 0, 38.37], 'Nathaniel Dell': [0, 0, 0, 0, 159.0, 148.61], 'Nelson Agholor': [92.0, 177.0, 99.0, 73.0, 92.0, 102.46], 'Nick Westbrook': [0, 6.0, 102.0, 78.0, 78.0, 64.0], 'Nico Collins': [0, 0, 76.0, 92.0, 254.0, 272.39], 'Noah Brown': [0, 26.0, 30.0, 110.0, 98.0, 136.86], 'Nsimba Webster': [0, -1.0, 0, 3.0, 0, 2.3], 'Odell Beckham Jr.': [195.0, 83.0, 120.0, 0, 102.0, 118.29], 'Olabisi Johnson': [72.0, 32.0, 0, 0, 0, 39.14], 'Olamide Zaccheaus': [20.0, 52.0, 84.0, 103.0, 34.0, 51.76], 'Parker Washington': [0, 0, 0, 0, 38.0, 27.14], 'Parris Campbell': [36.0, 13.0, 30.0, 141.0, 28.0, 44.91], 'Paul Richardson': [61.0, 0, 0, 0, 0, 50.93], 'Penny Hart': [0, 2.0, 10.0, 4.0, 0, 13.03], 'Pharoh Cooper': [49.0, 11.0, 6.0, 2.0, 0, -8.49], 'Phillip Dorsett': [96.0, 0, 16.0, 46.0, 0, 53.45], 'Preston Williams': [89.0, 71.0, 12.0, 0, 0, -129.79], 'Puka Nacua': [0, 0, 0, 0, 288.0, 312.18], 'Quentin Johnston': [0, 0, 0, 0, 86.0, 90.08], 'Quez Watkins': [0, 22.0, 108.0, 79.0, 33.0, 66.17], 'Quincy Enunwa': [0.0, 0, 0, 0, 0, -1.49], 'Quintez Cephus': [0, 62.0, 47.0, 3.0, 0, -116.01], 'Racey McMath': [0, 0, 1.0, 5.0, 0, 7.77], 'Rakim Jarrett': [0, 0, 0, 0, 8.0, 11.98], 'Randall Cobb': [150.0, 95.0, 91.0, 76.0, 15.0, -42.69], 'Rashard Davis': [2.0, 0, 0, 0, 0, 2.72], 'Rashard Higgins': [14.0, 115.0, 52.0, 0, 0, 57.27], 'Rashee Rice': [0, 0, 0, 0, 207.0, 196.81], 'Rashid Shaheed': [0, 0, 0, 94.0, 142.0, 150.71], 'Rashod Bateman': [0, 0, 99.0, 51.0, 68.0, 78.47], 'Ray Ray McCloud': [-1.0, 30.0, 62.0, 54.0, 26.0, 28.06], 'Richie James': [25.0, 63.0, 0, 129.0, 17.0, 23.35], 'Rico Gafford': [13.0, 0, 0, 0, 0, 13.24], 'Riley Ridley': [12.0, 7.0, 0, 0, 0, 7.56], 'River Cracraft': [0, 9.0, 0, 29.0, 25.0, 24.82], 'Robbie Chosen': [156.0, 217.0, 131.0, 51.0, 20.0, 46.2], 'Robert Davis': [3.0, 0, 0, 0, 0, 2.93], 'Robert Foster': [11.0, 4.0, 0, 0, 0, 7.14], 'Robert Woods': [220.0, 236.0, 131.0, 109.0, 84.0, 32.78], 'Romeo Doubs': [0, 0, 0, 97.0, 168.0, 141.24], 'Rondale Moore': [0, 0, 100.0, 86.0, 95.0, 62.28], 'Ronnie Bell': [0, 0, 0, 0, 29.0, 13.66], 'Russell Gage': [92.0, 176.0, 160.0, 119.0, 0, 42.82], 'Russell Shepard': [4.0, 0, 0, 0, 0, 4.61], 'Ryan Grant': [5.0, 0, 0, 0, 0, 2.3], 'Ryan Switzer': [10.0, 0, 0, 0, 0, 5.03], 'Sammy Watkins': [132.0, 85.0, 65.0, 43.0, 0, 24.43], 'Samori Toure': [0, 0, 0, 17.0, 15.0, 15.77], 'Scott Miller': [37.0, 96.0, 17.0, 37.0, 36.0, 44.74], 'Seth Roberts': [54.0, 6.0, 0, 0, 0, 5.88], 'Seth Williams': [0, 0, 4.0, 0, 0, 6.51], 'Shi Smith': [0, 0, 16.0, 58.0, 0, 61.66], 'Simi Fehoko': [0, 0, 0, 5.0, 7.0, 1.24], 'Skyy Moore': [0, 0, 0, 42.0, 49.0, 50.72], 'Stanley Morgan': [3.0, 0, 2.0, 0, 0, 1.67], 'Stefon Diggs': [205.0, 320.0, 279.0, 309.0, 267.0, 252.67], 'Sterling Shepard': [136.0, 154.0, 75.0, 33.0, 17.0, -0.49], 'Steven Mitchell': [5.0, 10.0, 0, 0, 0, 11.98], 'Steven Sims': [98.0, 54.0, 0, 27.0, 5.0, 4.61], 'T.J. Jones': [12.0, 0, 0, 0, 0, 7.35], 'T.Y. Hilton': [120.0, 158.0, 69.0, 18.0, 0, 65.07], 'Tajae Sharpe': [77.0, 0, 43.0, 0, 0, 47.77], 'Tarik Black': [0, 0, 2.0, 0, 0, 1.45], 'Tavon Austin': [42.0, 4.0, 47.0, 0, 0, 43.96], 'Taylor Gabriel': [84.0, 0, 0, 0, 0, 73.66], 'Ted Ginn Jr.': [80.0, 6.0, 0, 0, 0, 7.77], 'Tee Higgins': [0, 187.0, 214.0, 214.0, 133.0, 62.02], 'Terrace Marshall': [0, 0, 28.0, 78.0, 30.0, 28.61], 'Terry Godwin': [0, 6.0, 0, 0, 0, 6.09], 'Terry McLaurin': [186.0, 218.0, 208.0, 220.0, 205.0, 210.29], 'Tevin Jones': [8.0, 0, 0, 0, 0, 12.19], 'Tim Jones': [0, 0, 0, 5.0, 17.0, 16.82], 'Tim Patrick': [35.0, 154.0, 147.0, 0, 0, 178.15], 'Tom Kennedy': [0, 0, 18.0, 20.0, 0, 29.03], 'Tommylee Lewis': [0, 2.0, 1.0, 0, 0, 0.82], 'Travis Benjamin': [8.0, 0, -1.0, 0, 0, -0.65], 'Travis Fulgham': [0, 110.0, 0, 0, 0, 112.82], 'Tre Tucker': [0, 0, 0, 0, 65.0, 69.03], "Tre'Quan Smith": [67.0, 98.0, 84.0, 48.0, 0, 71.17], 'Trent Sherfield': [10.0, 9.0, 20.0, 76.0, 21.0, 29.6], 'Trent Taylor': [0, 16.0, 6.0, 10.0, -1.0, -0.65], 'Trenton Irwin': [0, 1.0, 4.0, 59.0, 58.0, 62.01], 'Trevor Davis': [28.0, 0, 0, 0, 0, 22.72], 'Trey Palmer': [0, 0, 0, 0, 89.0, 80.4], 'Trey Quinn': [48.0, 0, 0, 0, 0, 41.03], 'Treylon Burks': [0, 0, 0, 88.0, 35.0, 45.87], 'Trinity Benson': [0, 0, 18.0, 0, 0, 21.03], 'Trishton Jackson': [0, 0, 0, 0, 4.0, 1.24], 'Ty Montgomery': [26.0, 15.0, 26.0, 10.0, 6.0, 7.22], 'Tylan Wallace': [0, 0, 3.0, 5.0, 2.0, 3.46], 'Tyler Boyd': [217.0, 186.0, 173.0, 160.0, 135.0, 108.21], 'Tyler Johnson': [0, 38.0, 66.0, 0, 8.0, 1.03], 'Tyler Lockett': [231.0, 260.0, 234.0, 231.0, 197.0, 203.14], 'Tyler Scott': [0, 0, 0, 0, 31.0, 34.72], 'Tyquan Thornton': [0, 0, 0, 60.0, 21.0, 18.51], 'Tyreek Hill': [182.0, 317.0, 286.0, 338.0, 370.0, 455.52], 'Tyrell Williams': [136.0, 0, 3.0, 0, 0, 2.3], 'Tyrie Cleveland': [0, 11.0, 0, 4.0, 0, 5.24], 'Tyron Johnson': [0, 76.0, 3.0, 1.0, 0, -5.04], 'Van 

In [111]:
import json
json_data = json.dumps(name_fantasy_dict, indent=4)
with open('../FantasyDashbord-/Flask/static/WRYearlyPoints.json','w') as json_file:
    json_file.write(json_data)

                Player  Predicted_Fantasy_Points_2024
0           A.J. Brown                         299.23
1           A.J. Green                         144.51
2           A.T. Perry                          51.14
3       Adam Humphries                          79.91
4         Adam Thielen                         186.99
..                 ...                            ...
415      Xavier Gipson                          47.56
416  Xavier Hutchinson                          18.30
417        Zach Pascal                         -18.96
418        Zay Flowers                         179.97
419          Zay Jones                          76.83

[420 rows x 2 columns]

                Player  Predicted_Fantasy_Points_2024
57         CeeDee Lamb                         539.21
16   Amon-Ra St. Brown                         468.82
404        Tyreek Hill                         455.52
38       Brandon Aiyuk                         415.12
326         Puka Nacua                         312.18
..                 ...                            ...
330     Quintez Cephus                        -116.01
325   Preston Williams                        -129.79
205      Jarvis Landry                        -146.00
288       Marvin Jones                        -158.88
78        Cole Beasley                        -194.55

[420 rows x 2 columns]