In [15]:
from pathlib import Path
import pandas as pd

In [16]:
nine = Path('../excels/QBs2019.csv')
twenty = Path('../excels/QBs2020.csv')
twentyone = Path('../excels/QBs2021.csv')
twentytwo = Path('../excels/QBs2022Updated.csv')
twentythree = Path('../excels/QBs2023Updated.csv')

In [17]:
d2019 = pd.read_csv(nine)
d2020 = pd.read_csv(twenty)
d2021 = pd.read_csv(twentyone)
d2022 = pd.read_csv(twentytwo)
d2023 = pd.read_csv(twentythree)

In [18]:
d1920 = pd.concat([d2019, d2020], ignore_index=True)

In [19]:
wr19 = Path('../excels/WR2019.csv')
wr20 = Path('../excels/WR2020.csv')
wr21 = Path('../excels/WR2021.csv')
wr22 = Path('../excels/WR2022.csv')
wr23 = Path('../excels/WR2023.csv')

In [20]:
w2019 = pd.read_csv(wr19)
w2020 = pd.read_csv(wr20)
w2021 = pd.read_csv(wr21)
w2022 = pd.read_csv(wr22)
w2023 = pd.read_csv(wr23)

In [21]:
WR201920 = pd.concat([w2019,w2020], ignore_index = True)

In [22]:
WR20202021 = pd.concat([WR201920,w2021], ignore_index=True)

In [23]:
WR20202021

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1,Sammy Watkins,WR,2019,KC@JAX,46.0,0,0,0,0,0,0,0,9,198,3
1,1,1,DeSean Jackson,WR,2019,WAS@PHI,35.0,0,0,0,0,0,0,0,8,154,2
2,2,1,John Ross,WR,2019,CIN@SEA,34.0,0,0,0,0,0,0,0,7,158,2
3,3,1,DeAndre Hopkins,WR,2019,HOU@NO,31.0,0,0,0,0,0,0,0,8,111,2
4,4,1,Marquise Brown,WR,2019,BAL@MIA,30.0,0,0,0,0,0,0,0,4,147,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5726,1994,18,Greg Ward,WR,2021,DAL@PHI,1.0,2,0,0,0,0,0,0,1,2,0
5727,1995,18,Alex Bachman,WR,2021,WAS@NYG,0.0,0,0,0,1,-3,0,0,0,0,0
5728,1996,18,Devin Duvernay,WR,2021,PIT@BAL,0.0,0,0,0,1,2,0,0,0,0,0
5729,1997,18,Brandon Zylstra,WR,2021,CAR@TB,0.0,0,0,0,0,0,0,0,0,0,0
5730,1998,18,Andre Roberts,WR,2021,LAC@LV,-1.0,0,0,0,0,0,1,0,0,0,0

In [24]:
WR20202021.drop('Unnamed: 0', axis=1, inplace=True)

In [25]:
WR202020212022 = pd.concat([WR20202021,w2022],ignore_index=True)

In [26]:
WR20202021202223 = pd.concat([WR202020212022,w2023], ignore_index = True)

In [27]:
WR20202021202223

,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs,Unnamed: 0
0,1,Sammy Watkins,WR,2019,KC@JAX,46.0,0,0,0,0,0,0,0,9,198,3,NaN
1,1,DeSean Jackson,WR,2019,WAS@PHI,35.0,0,0,0,0,0,0,0,8,154,2,NaN
2,1,John Ross,WR,2019,CIN@SEA,34.0,0,0,0,0,0,0,0,7,158,2,NaN
3,1,DeAndre Hopkins,WR,2019,HOU@NO,31.0,0,0,0,0,0,0,0,8,111,2,NaN
4,1,Marquise Brown,WR,2019,BAL@MIA,30.0,0,0,0,0,0,0,0,4,147,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9699,18,Calvin Austin,WR,2023,PIT@BAL,0.0,0,0,0,1,8,0,0,0,0,0,2028.0
9700,18,A.J. Brown,WR,2023,PHI@NYG,0.0,0,0,0,0,0,1,0,1,9,0,2029.0
9701,18,Dyami Brown,WR,2023,DAL@WAS,0.0,4,0,0,0,0,0,0,0,0,0,2030.0
9702,18,George Pickens,WR,2023,PIT@BAL,0.0,0,0,0,1,3,0,0,0,0,0,2031.0
9703,18,KaVontae Turpin,WR,2023,DAL@WAS,0.0,0,0,0,1,5,0,0,0,0,0,2032.0

In [28]:
d192021 = pd.concat([d1920,d2021], ignore_index=True)

In [29]:
d192021

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324,5,0,3,6,0,0,NaN,NaN,NaN
1,1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405,4,0,4,12,0,0,NaN,NaN,NaN
2,2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268,3,1,4,40,0,1,NaN,NaN,NaN
3,3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385,3,0,3,22,1,0,NaN,NaN,NaN
4,4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380,3,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1883,727,18.0,Marcus Mariota,QB,2021,LAC@LV,2.0,4,0,0,4,23,0,0,NaN,NaN,NaN
1884,728,18.0,Tim Boyle,QB,2021,GB@DET,0.0,0,0,0,1,-1,0,0,NaN,NaN,NaN
1885,729,18.0,Blaine Gabbert,QB,2021,CAR@TB,0.0,0,0,0,1,-1,0,0,NaN,NaN,NaN
1886,730,18.0,Cooper Rush,QB,2021,DAL@PHI,0.0,10,0,0,3,-4,0,0,NaN,NaN,NaN
1887,731,18.0,Mitchell Trubisky,QB,2021,NYJ@BUF,0.0,15,0,0,3,-3,0,0,NaN,NaN,NaN

In [30]:
d192022 = pd.concat([d192021,d2022], ignore_index=True)

In [31]:
d192022

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324,5,0,3,6,0,0,NaN,NaN,NaN
1,1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405,4,0,4,12,0,0,NaN,NaN,NaN
2,2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268,3,1,4,40,0,1,NaN,NaN,NaN
3,3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385,3,0,3,22,1,0,NaN,NaN,NaN
4,4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380,3,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,968,NaN,Chad Henne,QB,2022,KC@LV,0.0,0,0,0,2,-2,0,0,NaN,NaN,NaN
2516,969,NaN,Trace McSorley,QB,2022,ARI@SF,0.0,29,0,1,3,13,0,0,NaN,NaN,NaN
2517,970,NaN,Cooper Rush,QB,2022,DAL@WAS,0.0,0,0,0,0,0,0,0,NaN,NaN,NaN
2518,971,NaN,Kyle Trask,QB,2022,TB@ATL,0.0,23,0,0,0,0,0,0,NaN,NaN,NaN
2519,972,NaN,Tim Boyle,QB,2022,MIN@CHI,-3.0,33,0,2,2,-2,0,0,NaN,NaN,NaN

In [32]:
d20212223 = pd.concat([d192022,d2023], ignore_index=True)

In [33]:
d20212223

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3193,673,18.0,Jalen Hurts,QB,2023,PHI@NYG,0.0,NaN,NaN,1,2,4,0,0,NaN,NaN,NaN
3194,674,18.0,A.J. McCarron,QB,2023,CLE@CIN,0.0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
3195,675,18.0,Clayton Tune,QB,2023,SEA@ARI,0.0,NaN,NaN,0,1,1,0,0,NaN,NaN,NaN
3196,676,18.0,Bailey Zappe,QB,2023,NYJ@NE,0.0,NaN,NaN,2,3,13,0,0,NaN,NaN,NaN
3197,677,18.0,Logan Woodside,QB,2023,ATL@NO,-1.0,NaN,NaN,1,1,6,0,0,NaN,NaN,NaN

In [34]:
d192022

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324,5,0,3,6,0,0,NaN,NaN,NaN
1,1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405,4,0,4,12,0,0,NaN,NaN,NaN
2,2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268,3,1,4,40,0,1,NaN,NaN,NaN
3,3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385,3,0,3,22,1,0,NaN,NaN,NaN
4,4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380,3,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,968,NaN,Chad Henne,QB,2022,KC@LV,0.0,0,0,0,2,-2,0,0,NaN,NaN,NaN
2516,969,NaN,Trace McSorley,QB,2022,ARI@SF,0.0,29,0,1,3,13,0,0,NaN,NaN,NaN
2517,970,NaN,Cooper Rush,QB,2022,DAL@WAS,0.0,0,0,0,0,0,0,0,NaN,NaN,NaN
2518,971,NaN,Kyle Trask,QB,2022,TB@ATL,0.0,23,0,0,0,0,0,0,NaN,NaN,NaN
2519,972,NaN,Tim Boyle,QB,2022,MIN@CHI,-3.0,33,0,2,2,-2,0,0,NaN,NaN,NaN

In [35]:
d20212223 = pd.concat([d192022,d2023], ignore_index=True)

In [36]:
d20212223

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3193,673,18.0,Jalen Hurts,QB,2023,PHI@NYG,0.0,NaN,NaN,1,2,4,0,0,NaN,NaN,NaN
3194,674,18.0,A.J. McCarron,QB,2023,CLE@CIN,0.0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
3195,675,18.0,Clayton Tune,QB,2023,SEA@ARI,0.0,NaN,NaN,0,1,1,0,0,NaN,NaN,NaN
3196,676,18.0,Bailey Zappe,QB,2023,NYJ@NE,0.0,NaN,NaN,2,3,13,0,0,NaN,NaN,NaN
3197,677,18.0,Logan Woodside,QB,2023,ATL@NO,-1.0,NaN,NaN,1,1,6,0,0,NaN,NaN,NaN

In [37]:
d2023

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1,Tua Tagovailoa,QB,2023,MIA@LAC,33.0,1,5,5,1,0,NaN,NaN,NaN
1,1,1,Mac Jones,QB,2023,PHI@NE,29.0,1,2,15,0,0,NaN,NaN,NaN
2,2,1,Jordan Love,QB,2023,GB@CHI,28.0,0,3,12,0,0,NaN,NaN,NaN
3,3,1,Patrick Mahomes,QB,2023,DET@KC,23.0,1,6,45,0,0,NaN,NaN,NaN
4,4,1,Justin Herbert,QB,2023,MIA@LAC,22.0,0,5,17,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
673,673,18,Jalen Hurts,QB,2023,PHI@NYG,0.0,1,2,4,0,0,NaN,NaN,NaN
674,674,18,A.J. McCarron,QB,2023,CLE@CIN,0.0,0,0,0,0,0,NaN,NaN,NaN
675,675,18,Clayton Tune,QB,2023,SEA@ARI,0.0,0,1,1,0,0,NaN,NaN,NaN
676,676,18,Bailey Zappe,QB,2023,NYJ@NE,0.0,2,3,13,0,0,NaN,NaN,NaN
677,677,18,Logan Woodside,QB,2023,ATL@NO,-1.0,1,1,6,0,0,NaN,NaN,NaN

In [38]:
d20212223.to_csv('CompleteListofQBs.csv')

In [39]:
HBnine = Path('../excels/HB2019.csv')
HBtwenty = Path('../excels/HB2020.csv')
HBtwentyone = Path('../excels/HB2021.csv')
HBtwentytwo = Path('../excels/HB2022.csv')
HBtwentythree = Path('../excels/HB2023.csv')

In [40]:
rb2019 = pd.read_csv(HBnine)
rb2020 = pd.read_csv(HBtwenty)
rb2021 = pd.read_csv(HBtwentyone)
rb2022 = pd.read_csv(HBtwentytwo)
rb2023 = pd.read_csv(HBtwentythree)

In [41]:
hb1920 = pd.concat([rb2019, rb2020], ignore_index=True)

In [42]:
hb1920

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1.0,Christian McCaffrey,RB,2019,LA@CAR,42.0,0,0,0,19,128,0,2,10,81,0
1,1,1.0,Austin Ekeler,RB,2019,IND@LAC,38.0,0,0,0,12,58,0,1,6,96,2
2,2,1.0,Derrick Henry,RB,2019,TEN@CLE,28.0,0,0,0,19,84,0,1,1,75,1
3,3,1.0,Dalvin Cook,RB,2019,ATL@MIN,25.0,0,0,0,21,111,0,2,2,9,0
4,4,1.0,David Johnson,RB,2019,DET@ARI,25.0,0,0,0,18,82,0,0,6,55,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2769,1408,17.0,Giovani Bernard,RB,2020,BAL@CIN,0.0,0,0,0,3,7,0,0,0,0,0
2770,1409,17.0,AJ Dillon,RB,2020,GB@CHI,0.0,0,0,0,1,3,0,0,0,0,0
2771,1410,17.0,Dion Lewis,RB,2020,DAL@NYG,0.0,0,0,0,1,7,0,0,0,0,0
2772,1411,17.0,Artavis Pierce,RB,2020,GB@CHI,0.0,0,0,0,1,-1,0,0,0,0,0
2773,1412,17.0,Anthony Sherman,RB,2020,LAC@KC,0.0,0,0,0,1,6,0,0,0,0,0

In [43]:
hb1920.drop('Unnamed: 0', axis=1, inplace=True)

In [44]:
hb192021 = pd.concat([hb1920, rb2021], ignore_index=True)

In [45]:
hb192021

,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs,Unnamed: 0
0,1.0,Christian McCaffrey,RB,2019,LA@CAR,42.0,0,0,0,19,128,0,2,10,81,0,NaN
1,1.0,Austin Ekeler,RB,2019,IND@LAC,38.0,0,0,0,12,58,0,1,6,96,2,NaN
2,1.0,Derrick Henry,RB,2019,TEN@CLE,28.0,0,0,0,19,84,0,1,1,75,1,NaN
3,1.0,Dalvin Cook,RB,2019,ATL@MIN,25.0,0,0,0,21,111,0,2,2,9,0,NaN
4,1.0,David Johnson,RB,2019,DET@ARI,25.0,0,0,0,18,82,0,0,6,55,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4222,18.0,Ty Johnson,RB,2021,NYJ@BUF,0.0,0,0,0,1,-1,0,0,0,0,0,1448.0
4223,18.0,Kene Nwangwu,RB,2021,CHI@MIN,0.0,0,0,0,1,4,0,0,0,0,0,1449.0
4224,18.0,Craig Reynolds,RB,2021,GB@DET,0.0,0,0,0,3,2,0,0,0,0,0,1450.0
4225,18.0,Mekhi Sargent,RB,2021,IND@JAX,0.0,0,0,0,1,2,0,0,0,0,0,1451.0
4226,18.0,Ty'Son Williams,RB,2021,PIT@BAL,0.0,0,0,0,1,4,0,0,0,0,0,1452.0

In [46]:
hb19202122 = pd.concat([hb192021, rb2022], ignore_index=True)

In [47]:
hb1920212223=pd.concat([hb19202122, rb2023], ignore_index=True)

In [48]:
hb1920212223

,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs,Unnamed: 0
0,1.0,Christian McCaffrey,RB,2019,LA@CAR,42.0,0,0,0,19,128,0,2,10,81,0,NaN
1,1.0,Austin Ekeler,RB,2019,IND@LAC,38.0,0,0,0,12,58,0,1,6,96,2,NaN
2,1.0,Derrick Henry,RB,2019,TEN@CLE,28.0,0,0,0,19,84,0,1,1,75,1,NaN
3,1.0,Dalvin Cook,RB,2019,ATL@MIN,25.0,0,0,0,21,111,0,2,2,9,0,NaN
4,1.0,David Johnson,RB,2019,DET@ARI,25.0,0,0,0,18,82,0,0,6,55,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7072,18.0,D'Ernest Johnson,RB,2023,JAX@TEN,0.0,0,0,0,1,-1,0,0,0,0,0,1389.0
7073,18.0,Joshua Kelley,RB,2023,KC@LAC,0.0,0,0,0,2,1,0,0,0,0,0,1390.0
7074,18.0,Jaleel McLaughlin,RB,2023,DEN@LV,0.0,0,0,0,4,6,0,0,0,0,0,1391.0
7075,18.0,Boston Scott,RB,2023,PHI@NYG,0.0,0,0,0,3,5,0,0,0,0,0,1392.0
7076,18.0,Trayveon Williams,RB,2023,CLE@CIN,0.0,0,0,0,1,-2,0,0,0,0,0,1393.0

In [49]:
hb1920212223.to_csv('CompleteListofRBs.csv')

In [50]:
QB = Path('../excels/CompleteListofQBs.csv')
RB = Path('../excels/CompleteListofRBs.csv')

In [51]:
QBdf = pd.read_csv(QB)
RBdf = pd.read_csv(RB)

In [52]:
QBdf

,Unnamed: 0.1,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1,1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,2,2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,3,3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,4,4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3193,3193,673,18.0,Jalen Hurts,QB,2023,PHI@NYG,0.0,NaN,NaN,1,2,4,0,0,NaN,NaN,NaN
3194,3194,674,18.0,A.J. McCarron,QB,2023,CLE@CIN,0.0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
3195,3195,675,18.0,Clayton Tune,QB,2023,SEA@ARI,0.0,NaN,NaN,0,1,1,0,0,NaN,NaN,NaN
3196,3196,676,18.0,Bailey Zappe,QB,2023,NYJ@NE,0.0,NaN,NaN,2,3,13,0,0,NaN,NaN,NaN
3197,3197,677,18.0,Logan Woodside,QB,2023,ATL@NO,-1.0,NaN,NaN,1,1,6,0,0,NaN,NaN,NaN

In [53]:
QBdf.drop('Unnamed: 0.1', axis=1, inplace=True)

In [54]:
QBdf.drop('Unnamed: 0', axis=1, inplace=True)

In [55]:
RBdf.drop('Unnamed: 0', axis=1, inplace=True)

In [56]:
RBdf.drop('Unnamed: 0.1', axis=1, inplace=True)

In [57]:
QBdf

,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3193,18.0,Jalen Hurts,QB,2023,PHI@NYG,0.0,NaN,NaN,1,2,4,0,0,NaN,NaN,NaN
3194,18.0,A.J. McCarron,QB,2023,CLE@CIN,0.0,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
3195,18.0,Clayton Tune,QB,2023,SEA@ARI,0.0,NaN,NaN,0,1,1,0,0,NaN,NaN,NaN
3196,18.0,Bailey Zappe,QB,2023,NYJ@NE,0.0,NaN,NaN,2,3,13,0,0,NaN,NaN,NaN
3197,18.0,Logan Woodside,QB,2023,ATL@NO,-1.0,NaN,NaN,1,1,6,0,0,NaN,NaN,NaN

In [58]:
QBRB = pd.concat([QBdf,RBdf], ignore_index=True)

In [59]:
QBRB.to_csv('CompleteListofQBsRBs.csv')

In [60]:
WRdf = WR20202021202223

In [61]:
WRdf

,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs,Unnamed: 0
0,1,Sammy Watkins,WR,2019,KC@JAX,46.0,0,0,0,0,0,0,0,9,198,3,NaN
1,1,DeSean Jackson,WR,2019,WAS@PHI,35.0,0,0,0,0,0,0,0,8,154,2,NaN
2,1,John Ross,WR,2019,CIN@SEA,34.0,0,0,0,0,0,0,0,7,158,2,NaN
3,1,DeAndre Hopkins,WR,2019,HOU@NO,31.0,0,0,0,0,0,0,0,8,111,2,NaN
4,1,Marquise Brown,WR,2019,BAL@MIA,30.0,0,0,0,0,0,0,0,4,147,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9699,18,Calvin Austin,WR,2023,PIT@BAL,0.0,0,0,0,1,8,0,0,0,0,0,2028.0
9700,18,A.J. Brown,WR,2023,PHI@NYG,0.0,0,0,0,0,0,1,0,1,9,0,2029.0
9701,18,Dyami Brown,WR,2023,DAL@WAS,0.0,4,0,0,0,0,0,0,0,0,0,2030.0
9702,18,George Pickens,WR,2023,PIT@BAL,0.0,0,0,0,1,3,0,0,0,0,0,2031.0
9703,18,KaVontae Turpin,WR,2023,DAL@WAS,0.0,0,0,0,1,5,0,0,0,0,0,2032.0

In [62]:
QBRB = Path('../excels/CompleteListofQBsRBs.csv')

In [63]:
QBRBdf = pd.read_csv(QBRB)

In [64]:
QBRBdf

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10270,10270,18.0,D'Ernest Johnson,RB,2023,JAX@TEN,0.0,0.0,0.0,0,1,-1,0,0,0.0,0.0,0.0
10271,10271,18.0,Joshua Kelley,RB,2023,KC@LAC,0.0,0.0,0.0,0,2,1,0,0,0.0,0.0,0.0
10272,10272,18.0,Jaleel McLaughlin,RB,2023,DEN@LV,0.0,0.0,0.0,0,4,6,0,0,0.0,0.0,0.0
10273,10273,18.0,Boston Scott,RB,2023,PHI@NYG,0.0,0.0,0.0,0,3,5,0,0,0.0,0.0,0.0
10274,10274,18.0,Trayveon Williams,RB,2023,CLE@CIN,0.0,0.0,0.0,0,1,-2,0,0,0.0,0.0,0.0

In [65]:
QBRBdf

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10270,10270,18.0,D'Ernest Johnson,RB,2023,JAX@TEN,0.0,0.0,0.0,0,1,-1,0,0,0.0,0.0,0.0
10271,10271,18.0,Joshua Kelley,RB,2023,KC@LAC,0.0,0.0,0.0,0,2,1,0,0,0.0,0.0,0.0
10272,10272,18.0,Jaleel McLaughlin,RB,2023,DEN@LV,0.0,0.0,0.0,0,4,6,0,0,0.0,0.0,0.0
10273,10273,18.0,Boston Scott,RB,2023,PHI@NYG,0.0,0.0,0.0,0,3,5,0,0,0.0,0.0,0.0
10274,10274,18.0,Trayveon Williams,RB,2023,CLE@CIN,0.0,0.0,0.0,0,1,-2,0,0,0.0,0.0,0.0

In [66]:
CompleteList = pd.concat([QBRBdf,WRdf], ignore_index = True)

In [67]:
CompleteList

,Unnamed: 0,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,0.0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1.0,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,2.0,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,3.0,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,4.0,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19974,2028.0,18.0,Calvin Austin,WR,2023,PIT@BAL,0.0,0.0,0.0,0,1,8,0,0,0.0,0.0,0.0
19975,2029.0,18.0,A.J. Brown,WR,2023,PHI@NYG,0.0,0.0,0.0,0,0,0,1,0,1.0,9.0,0.0
19976,2030.0,18.0,Dyami Brown,WR,2023,DAL@WAS,0.0,4.0,0.0,0,0,0,0,0,0.0,0.0,0.0
19977,2031.0,18.0,George Pickens,WR,2023,PIT@BAL,0.0,0.0,0.0,0,1,3,0,0,0.0,0.0,0.0
19978,2032.0,18.0,KaVontae Turpin,WR,2023,DAL@WAS,0.0,0.0,0.0,0,1,5,0,0,0.0,0.0,0.0

In [68]:
CompleteList.drop('Unnamed: 0', axis=1, inplace=True)

In [69]:
CompleteList

,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19974,18.0,Calvin Austin,WR,2023,PIT@BAL,0.0,0.0,0.0,0,1,8,0,0,0.0,0.0,0.0
19975,18.0,A.J. Brown,WR,2023,PHI@NYG,0.0,0.0,0.0,0,0,0,1,0,1.0,9.0,0.0
19976,18.0,Dyami Brown,WR,2023,DAL@WAS,0.0,4.0,0.0,0,0,0,0,0,0.0,0.0,0.0
19977,18.0,George Pickens,WR,2023,PIT@BAL,0.0,0.0,0.0,0,1,3,0,0,0.0,0.0,0.0
19978,18.0,KaVontae Turpin,WR,2023,DAL@WAS,0.0,0.0,0.0,0,1,5,0,0,0.0,0.0,0.0

In [71]:
CompleteList

,Week,Name,Position,Year,Game,Fantasy Points,PassingYards,PassingTDs,Ints,Rush Attempts,Rush Yards,Fumbles,RushTDs,Receptions,Receiving Yards,Receiving TDs
0,1.0,Lamar Jackson,QB,2019,BAL@MIA,42.0,324.0,5.0,0,3,6,0,0,NaN,NaN,NaN
1,1.0,Dak Prescott,QB,2019,NYG@DAL,41.0,405.0,4.0,0,4,12,0,0,NaN,NaN,NaN
2,1.0,Deshaun Watson,QB,2019,HOU@NO,36.0,268.0,3.0,1,4,40,0,1,NaN,NaN,NaN
3,1.0,Matthew Stafford,QB,2019,DET@ARI,34.0,385.0,3.0,0,3,22,1,0,NaN,NaN,NaN
4,1.0,Case Keenum,QB,2019,WAS@PHI,33.0,380.0,3.0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19974,18.0,Calvin Austin,WR,2023,PIT@BAL,0.0,0.0,0.0,0,1,8,0,0,0.0,0.0,0.0
19975,18.0,A.J. Brown,WR,2023,PHI@NYG,0.0,0.0,0.0,0,0,0,1,0,1.0,9.0,0.0
19976,18.0,Dyami Brown,WR,2023,DAL@WAS,0.0,4.0,0.0,0,0,0,0,0,0.0,0.0,0.0
19977,18.0,George Pickens,WR,2023,PIT@BAL,0.0,0.0,0.0,0,1,3,0,0,0.0,0.0,0.0
19978,18.0,KaVontae Turpin,WR,2023,DAL@WAS,0.0,0.0,0.0,0,1,5,0,0,0.0,0.0,0.0

In [72]:
CompleteList.to_csv('CompleteDataSet.csv')